Repository rust-lang/rust-analyzer, pull requests merged in 2020-10, with the labels that each got.

#6148 Fix trait object hir formatting behind pointer and references
  crates/hir_ty/src/display.rs
  crates/ide/src/inlay_hints.rs
Labels: hacktoberfest-accepted

#6140 honour hover.content_format client capability
  crates/ide/src/hover.rs
  crates/ide/src/lib.rs
  crates/ide/src/markdown_remove.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers.rs
Labels: hacktoberfest-accepted

#6159 Document "*.mutable" trick in manual
  docs/user/manual.adoc
Labels: hacktoberfest-accepted

#6160 Add validation check for ambiguous trait objects
  crates/syntax/src/validation.rs
  crates/syntax/test_data/parser/err/0046_ambiguous_trait_object.rast
  crates/syntax/test_data/parser/err/0046_ambiguous_trait_object.rs
  crates/syntax/test_data/parser/ok/0069_multi_trait_object.rast
  crates/syntax/test_data/parser/ok/0069_multi_trait_object.rs
Labels: A-ty, hacktoberfest-accepted

#6158 Fix for negative literals in macros
  crates/mbe/src/subtree_source.rs
Labels: A-macro, hacktoberfest-accepted

#6161 Bump chalk to use latest git to get upstream fix
  Cargo.lock
  crates/hir_ty/Cargo.toml
  crates/hir_ty/src/traits/chalk.rs
  crates/hir_ty/src/traits/chalk/mapping.rs
  editors/code/package.json
Labels: dependencies, hacktoberfest-accepted

#6173 Bump rustc_lexer, cfg-if to 1.0 and add new license to check
  Cargo.lock
  crates/profile/Cargo.toml
  crates/syntax/Cargo.toml
  xtask/tests/tidy.rs
Labels: hacktoberfest-accepted

#6176 add eprintln in fmt-like postfix
  crates/ide/src/completion/complete_postfix/format_like.rs
Labels: hacktoberfest-accepted

#6153 Improve prime_caches and display its progress
  crates/base_db/src/input.rs
  crates/ide/src/lib.rs
  crates/ide/src/prime_caches.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/thread_pool.rs
Labels: hacktoberfest-accepted

#6137 add a new TextMate grammar
  editors/code/rust.tmGrammar.json
Labels: hacktoberfest-accepted

#6222 Fix stackoverflow in insert_use::recursive_merge
  crates/assists/src/handlers/merge_imports.rs
  crates/assists/src/handlers/replace_qualified_name_with_use.rs
  crates/assists/src/utils/insert_use.rs
Labels: hacktoberfest-accepted

#6230 Log around sysroot discovery
  crates/project_model/src/sysroot.rs
Labels: hacktoberfest-accepted

#6234 Fix hover over field pattern shorthand
  crates/ide/src/hover.rs
Labels: hacktoberfest-accepted

#6243 Clarify classification API
  crates/assists/src/handlers/add_turbo_fish.rs
  crates/assists/src/handlers/expand_glob_import.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/goto_definition.rs
  crates/ide/src/hover.rs
  crates/ide/src/references.rs
  crates/ide/src/references/rename.rs
  crates/ide/src/syntax_highlighting.rs
  crates/ide_db/src/defs.rs
  crates/ide_db/src/imports_locator.rs
  crates/ide_db/src/search.rs
Labels: hacktoberfest-accepted

#6244 Document awkward names
  docs/dev/style.md
Labels: hacktoberfest-accepted

#6220 implement binary operator overloading type inference
  crates/hir_ty/src/infer.rs
  crates/hir_ty/src/infer/expr.rs
  crates/hir_ty/src/tests/simple.rs
Labels: hacktoberfest-accepted

#6246 Follow symlinks when walking project trees
  crates/vfs-notify/src/lib.rs
Labels: hacktoberfest-accepted

#6245 Update GNOME Builder docs
  docs/user/manual.adoc
Labels: hacktoberfest-accepted

#6253 Document change of 'cargo' Runnable kind in lsp-extensions.md
  docs/dev/lsp-extensions.md
Labels: hacktoberfest-accepted

#6248 Textmate grammar: prevent early termination of raw strings with hash (closes #6042)
  editors/code/rust.tmGrammar.json
Labels: hacktoberfest-accepted

#6274 Check cargoExtraArgs for undefined before using
  editors/code/src/run.ts
Labels: hacktoberfest-accepted

#6266 Generate diagnostics docs
  .gitignore
  crates/hir_def/src/diagnostics.rs
  crates/hir_ty/src/diagnostics.rs
  xtask/src/codegen.rs
  xtask/src/codegen/gen_assists_docs.rs
  xtask/src/codegen/gen_diagnostic_docs.rs
  xtask/src/codegen/gen_feature_docs.rs
  xtask/src/codegen/gen_parser_tests.rs
  xtask/src/release.rs
  xtask/tests/tidy.rs
Labels: hacktoberfest-accepted

#6256 Assist: replace string with char
  crates/assists/src/handlers/replace_string_with_char.rs
  crates/assists/src/lib.rs
  crates/assists/src/tests/generated.rs
Labels: hacktoberfest-accepted

#6109 add completions for clippy lint in attributes
  crates/completion/src/complete_attribute.rs
  crates/completion/src/generated_features.rs
  crates/completion/src/generated_lint_completions.rs
  crates/completion/src/lib.rs
  docs/user/generated_diagnostic.adoc
  xtask/src/codegen.rs
  xtask/src/codegen/gen_lint_completions.rs
  xtask/tests/tidy.rs
Labels: hacktoberfest-accepted

#6259 allow xtask install --client[=CLIENT] to specify client
  xtask/src/install.rs
  xtask/src/main.rs
Labels: hacktoberfest-accepted

#6270 Update crates
  Cargo.lock
  crates/flycheck/Cargo.toml
  crates/proc_macro_srv/Cargo.toml
  crates/project_model/Cargo.toml
Labels: hacktoberfest-accepted

#6337 Fix indentation of inserted use statements
  crates/assists/src/utils/insert_use.rs
  crates/test_utils/src/lib.rs
Labels: hacktoberfest-accepted

#6344 Bump deps
  Cargo.lock
  crates/hir_ty/Cargo.toml
  crates/ide_db/Cargo.toml
  crates/rust-analyzer/Cargo.toml
  crates/syntax/Cargo.toml
Labels: hacktoberfest-accepted

#6353 Get rid of FAKE_PLACEHOLDER
  crates/hir_ty/src/traits/chalk/mapping.rs
Labels: hacktoberfest-accepted

#6354 Add tracing to main rust-analyzer binary
  Cargo.lock
  crates/hir_ty/Cargo.toml
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/bin/main.rs
Labels: hacktoberfest-accepted

#6357 Don't keep parens around with remove-dbg
  crates/assists/src/handlers/remove_dbg.rs
Labels: hacktoberfest-accepted

#6360 Fix unary minus highlighting
  crates/ide/src/syntax_highlighting.rs
  crates/ide/src/syntax_highlighting/test_data/highlighting.html
  crates/ide/src/syntax_highlighting/tests.rs
Labels: hacktoberfest-accepted

#6350 Make IncorrectDiagnostic match rustc by copying rustc's code.
  crates/hir_ty/src/diagnostics/decl_check/case_conv.rs
Labels: hacktoberfest-accepted

#6347 Support insertion in SyntaxRewriter
  crates/syntax/src/algo.rs
Labels: hacktoberfest-accepted

#6333 Don't interpret type path as part of visibility.
  crates/assists/src/handlers/move_guard.rs
  crates/parser/src/grammar.rs
  crates/syntax/test_data/parser/inline/ok/0153_pub_parens_typepath.rast
  crates/syntax/test_data/parser/inline/ok/0153_pub_parens_typepath.rs
Labels: hacktoberfest-accepted

#6313 Latest proposed LSP 3.16.0 and refresh semantic tokens
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/caps.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
  crates/rust-analyzer/src/diagnostics/test_data/handles_macro_location.txt
  crates/rust-analyzer/src/diagnostics/test_data/macro_compiler_error.txt
  crates/rust-analyzer/src/diagnostics/test_data/rustc_incompatible_type_for_trait.txt
  crates/rust-analyzer/src/diagnostics/test_data/rustc_mismatched_type.txt
  crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
  crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
  crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
  crates/rust-analyzer/src/diagnostics/test_data/rustc_wrong_number_of_parameters.txt
  crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
  crates/rust-analyzer/src/diagnostics/to_proto.rs
  crates/rust-analyzer/src/handlers.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/to_proto.rs
  editors/code/package-lock.json
  editors/code/package.json
  editors/code/src/util.ts
Labels: hacktoberfest-accepted

#6351 Organized completions
  crates/completion/src/completions.rs
  crates/completion/src/completions/attribute.rs
  crates/completion/src/completions/dot.rs
  crates/completion/src/completions/fn_param.rs
  crates/completion/src/completions/keyword.rs
  crates/completion/src/completions/macro_in_item_position.rs
  crates/completion/src/completions/mod_.rs
  crates/completion/src/completions/pattern.rs
  crates/completion/src/completions/postfix.rs
  crates/completion/src/completions/postfix/format_like.rs
  crates/completion/src/completions/qualified_path.rs
  crates/completion/src/completions/record.rs
  crates/completion/src/completions/snippet.rs
  crates/completion/src/completions/trait_impl.rs
  crates/completion/src/completions/unqualified_path.rs
  crates/completion/src/config.rs
  crates/completion/src/context.rs
  crates/completion/src/generated_lint_completions.rs
  crates/completion/src/item.rs
  crates/completion/src/lib.rs
  crates/completion/src/test_utils.rs
  xtask/src/codegen/gen_lint_completions.rs
Labels: hacktoberfest-accepted

#6257 Don't suggest extracting out 1-tuple enum variants
  crates/assists/src/handlers/extract_struct_from_enum_variant.rs
Labels: hacktoberfest-accepted

#6376 Avoid impls_fnonce to return true when the trait solving is ambiguous
  crates/hir/src/code_model.rs
  crates/hir_ty/src/method_resolution.rs
  crates/ide/src/syntax_highlighting/test_data/highlighting.html
  crates/ide/src/syntax_highlighting/tests.rs
Labels: hacktoberfest-accepted

#6383 Update client install command in dev docs
  docs/dev/README.md
Labels: hacktoberfest-accepted

#6382 Set font-wieght: normal on inlay hints
  editors/code/src/inlay_hints.ts
Labels: hacktoberfest-accepted

#6379 Highlight never type as BuiltinType
  crates/ide/src/syntax_highlighting.rs
  crates/ide/src/syntax_highlighting/test_data/highlighting.html
  crates/ide/src/syntax_highlighting/tests.rs
Labels: hacktoberfest-accepted

#6392 Also set textDecoration: none on inlay hints
  editors/code/src/inlay_hints.ts
Labels: hacktoberfest-accepted

#6384 add doctest runnables on struct
  crates/ide/src/runnables.rs
Labels: hacktoberfest-accepted

#6398 cargo update
  Cargo.lock
Labels: hacktoberfest-accepted

#6403 docs: Update Neovim nvim-lspconfig repository link
  docs/user/manual.adoc
Labels: hacktoberfest-accepted

#6411 remove FIXME after rust 1.47 comes out
  crates/project_model/src/sysroot.rs
Labels: hacktoberfest-accepted
