Repository rust-lang/rust-analyzer, pull requests merged in 2023-10, with the labels that each got.

#15701 fix: strip base prefix in `layout_scalar_valid_range`
  crates/hir-ty/src/layout/adt.rs
Labels: S-waiting-on-review

#15698 fix: allow more kinds of if let patterns in guarded return assist
  crates/ide-assists/src/handlers/convert_to_guarded_return.rs
Labels: S-waiting-on-review

#15709 fix: Recognize custom main function as binary entrypoint for runnables
  crates/hir-def/src/attr.rs
  crates/hir/src/lib.rs
  crates/ide/src/runnables.rs
Labels: S-waiting-on-review

#15700 feat: add assist for applying De Morgan's law to `Iterator::all` and `Iterator::any`
  crates/ide-assists/src/handlers/apply_demorgan.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15690 vscode: Fix line and col regexp for `rustc` problem matcher
  editors/code/package.json
Labels: S-waiting-on-review

#15707 Add configuration for the default action of the status bar click action in VSCode
  editors/code/package.json
  editors/code/src/config.ts
  editors/code/src/ctx.ts
Labels: S-waiting-on-review

#15641 fix: preceding QualifiedPathType for into_to_from assist
  crates/ide-assists/src/handlers/into_to_qualified_from.rs
Labels: S-waiting-on-author

#15668 feat: add backtick to surrounding and auto-closing pairs
  editors/code/language-configuration.json
Labels: S-waiting-on-review

#15712 minor: Remove repetitive words
  crates/ide/src/syntax_highlighting.rs
  crates/mbe/src/expander.rs
Labels: S-waiting-on-review

#15714 minor: Prepare for rust-bors
  .github/workflows/ci.yaml
  rust-bors.toml
Labels: S-waiting-on-review

#15718 Fix typos exec_intrinsic
  crates/hir-ty/src/mir/eval/shim.rs
Labels: S-waiting-on-review

#15721 Shrink PatPtr by swapping its AstPtr and Either wrap order
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/scope.rs
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/tests.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/no_such_field.rs
  crates/ide-diagnostics/src/handlers/private_assoc_item.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/syntax/src/ptr.rs
Labels: S-waiting-on-review

#15600 fix: ensure `rustfmt` runs when configured with `./`
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-author

#15725 internal: fix automatic rustc/rustdoc lint generation
  crates/ide-db/src/generated/lints.rs
  crates/ide-db/src/tests/sourcegen_lints.rs
Labels: S-waiting-on-review

#15681 Add config option to use `rust-analyzer` specific target dir
  crates/flycheck/src/lib.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#15713 Do flyimport completions by prefix search for short paths
  crates/hir-def/src/import_map.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/tests/flyimport.rs
  crates/ide-db/src/imports/import_assets.rs
  crates/ide-db/src/items_locator.rs
  crates/ide-db/src/symbol_index.rs
Labels: S-waiting-on-review

#15696 feat: implement tuple return type to tuple struct assist
  crates/hir-ty/src/diagnostics/decl_check/case_conv.rs
  crates/ide-assists/src/handlers/convert_tuple_return_type_to_struct.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
  crates/stdx/src/lib.rs
Labels: S-waiting-on-author

#15618 internal: port anymap
  Cargo.lock
  Cargo.toml
  crates/hir-def/Cargo.toml
  crates/hir-def/src/dyn_map.rs
  crates/rust-analyzer/tests/slow-tests/tidy.rs
  crates/stdx/src/anymap.rs
  crates/stdx/src/lib.rs
Labels: S-waiting-on-author

#15728 feat: vscode: Support opening local documentation if available
  editors/code/src/client.ts
  editors/code/src/commands.ts
  editors/code/src/lsp_ext.ts
Labels: S-waiting-on-author

#15744 fix: add diagnostics messages for chars and byte literal errors
  crates/parser/src/lexed_str.rs
  crates/parser/test_data/lexer/err/byte_char_literals.rast
  crates/parser/test_data/lexer/err/byte_char_literals.rs
  crates/parser/test_data/lexer/err/char_literals.rast
  crates/parser/test_data/lexer/err/char_literals.rs
  crates/parser/test_data/lexer/ok/byte_strings.rast
  crates/parser/test_data/lexer/ok/byte_strings.rs
  crates/parser/test_data/lexer/ok/chars.rast
  crates/parser/test_data/lexer/ok/chars.rs
Labels: S-waiting-on-review

#15745 docs: Add Zed to IDE list.
  docs/user/manual.adoc
Labels: S-waiting-on-review

#15743 add replace_is_some_with_if_let_some assist
  crates/ide-assists/src/handlers/replace_is_some_with_if_let_some.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15752 feat: add replace_is_ok_with_if_let_ok assist
  crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
  crates/ide-assists/src/handlers/replace_is_some_with_if_let_some.rs
  crates/ide-assists/src/lib.rs
Labels: S-waiting-on-review

#15756 fix typo in mbe/lib.rs comment
  crates/mbe/src/lib.rs
Labels: S-waiting-on-review

#15760 make mir::ProjectionStore-impls pub-accessible
  crates/hir-ty/src/mir.rs
Labels: S-waiting-on-review

#15755 fix: make cursor select at _tmp
  crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15762 fix: Fix metrics workflow to use deploy key
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#15691 Update rustc_abi dependency
  Cargo.lock
  crates/hir-def/src/data/adt.rs
  crates/hir-ty/src/layout.rs
  crates/hir-ty/src/layout/adt.rs
  crates/hir/src/lib.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/view_memory_layout.rs
  crates/rustc-dependencies/Cargo.toml
  crates/rustc-dependencies/src/lib.rs
Labels: S-waiting-on-review

#15764 Expand Emacs documentation
  docs/user/manual.adoc
Labels: S-waiting-on-review

#15769 internal: Create `~/.ssh` before writing deploy key
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#15770 internal: Fix metrics repo url
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#15746 String literals diagnose
  crates/parser/src/lexed_str.rs
  crates/parser/test_data/lexer/err/byte_char_literals.rast
  crates/parser/test_data/lexer/err/byte_char_literals.rs
  crates/parser/test_data/lexer/err/byte_strings.rast
  crates/parser/test_data/lexer/err/byte_strings.rs
  crates/parser/test_data/lexer/err/c_strings.rast
  crates/parser/test_data/lexer/err/c_strings.rs
  crates/parser/test_data/lexer/err/strings.rast
  crates/parser/test_data/lexer/err/strings.rs
Labels: S-waiting-on-review

#15775 refactor: change generated variable name
  crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review, S-waiting-on-author, has-merge-commits

#15779 Add command for only opening external docs and attempt to fix vscode-remote issue
  editors/code/package.json
  editors/code/src/commands.ts
  editors/code/src/lsp_ext.ts
  editors/code/src/main.ts
Labels: S-waiting-on-review

#15783 internal: Free up some disk space on auto-publish
  .github/workflows/autopublish.yaml
Labels: S-waiting-on-review

#15736 fix: add incorrect case diagnostics for module names
  crates/hir-def/src/lib.rs
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/incorrect_case.rs
Labels: S-waiting-on-review

#15727 feat: generate descriptors for all unstable features
  crates/ide-db/src/generated/lints.rs
  crates/ide-db/src/tests/sourcegen_lints.rs
Labels: S-waiting-on-review

#15786 fix: Fix VS Code detection for Insiders version
  crates/rust-analyzer/src/bin/main.rs
Labels: S-waiting-on-review

#15789 Store binding mode for each instance of a binding independently
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/diagnostics/match_check.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/hir/src/source_analyzer.rs
  crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
Labels: S-waiting-on-review

#15780 fix: import trait if needed for `unqualify_method_call` assist
  crates/ide-assists/src/handlers/unqualify_method_call.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15806 internal: scip: update crate to version 0.3.1.
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/cli/scip.rs
Labels: S-waiting-on-review

#15809 feat: make extract_variable assist in place
  crates/ide-assists/src/handlers/extract_variable.rs
Labels: S-waiting-on-review

#15812 Fix some typos
  crates/hir-ty/src/mir/eval.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/syntax/src/tests/sourcegen_ast.rs
Labels: S-waiting-on-review

#15815 chore: fix urls in guide.md
  docs/dev/guide.md
Labels: S-waiting-on-review

#15788 feat: import trait with alias
  crates/ide-assists/src/handlers/auto_import.rs
  crates/ide-db/src/imports/insert_use.rs
Labels: S-waiting-on-review
