Repository rust-lang/rust-analyzer, pull requests merged in 2023-09, with the labels that each got.

#15542 Less `once_cell` more `std`
  .cargo/config.toml
  Cargo.lock
  crates/hir-def/src/attr/builtin.rs
  crates/hir-def/src/lower.rs
  crates/ide/src/typing.rs
  crates/intern/Cargo.toml
  crates/intern/src/lib.rs
Labels: S-waiting-on-review

#15543 Remove some allocations in borrowck
  crates/hir-ty/src/mir/borrowck.rs
Labels: S-waiting-on-review

#15544 Shuffle some locking around
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#15546 minor: remove the repetitive word
  crates/hir-def/src/nameres.rs
Labels: S-waiting-on-review

#15548 Restructure some modules in rust-analyzer crate
  crates/rust-analyzer/src/caps.rs
  crates/rust-analyzer/src/cli/lsif.rs
  crates/rust-analyzer/src/diagnostics.rs
  crates/rust-analyzer/src/diagnostics/to_proto.rs
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lib.rs
  crates/rust-analyzer/src/lsp.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/from_proto.rs
  crates/rust-analyzer/src/lsp/semantic_tokens.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/lsp/utils.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/markdown.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  crates/rust-analyzer/tests/slow-tests/tidy.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#15549 Add a few more `db.unwind_if_cancelled()` calls
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#15551 Move doc comment handling into ide-db
  crates/hir-def/src/attr.rs
  crates/hir/src/attrs.rs
  crates/hir/src/lib.rs
  crates/ide-completion/src/completions/attribute/derive.rs
  crates/ide-completion/src/completions/attribute/lint.rs
  crates/ide-completion/src/completions/extern_crate.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/completions/snippet.rs
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/literal.rs
  crates/ide-completion/src/render/macro_.rs
  crates/ide-completion/src/render/pattern.rs
  crates/ide-db/src/documentation.rs
  crates/ide-db/src/lib.rs
  crates/ide-db/src/rust_doc.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/doc_links/tests.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/lib.rs
  crates/ide/src/navigation_target.rs
  crates/ide/src/runnables.rs
  crates/ide/src/signature_help.rs
  crates/ide/src/syntax_highlighting/inject.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/lib.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/markdown.rs
Labels: S-waiting-on-review

#15552 Bump `rustc-perf` checkout for metrics, replace webrender, diesel and ripgrep with newer versions
  .github/workflows/metrics.yaml
  xtask/src/flags.rs
  xtask/src/metrics.rs
Labels: S-waiting-on-review

#15553 Add hyper-0.14.18 to metrics
  .github/workflows/metrics.yaml
  xtask/src/flags.rs
  xtask/src/metrics.rs
Labels: S-waiting-on-review

#15557 Parse builtin# syntax and add typechecking for builtin#offset_of expression
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/hir.rs
  crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/mutability.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir-ty/src/tests/traits.rs
  crates/ide-assists/src/handlers/convert_bool_then.rs
  crates/ide-assists/src/handlers/promote_local_to_const.rs
  crates/ide-assists/src/handlers/remove_dbg.rs
  crates/ide-assists/src/utils/suggest_name.rs
  crates/ide-db/src/syntax_helpers/node_ext.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/tests.rs
  crates/parser/src/grammar/expressions/atom.rs
  crates/parser/src/lexed_str.rs
  crates/parser/src/syntax_kind/generated.rs
  crates/parser/test_data/parser/inline/ok/0132_box_expr.rast
  crates/parser/test_data/parser/inline/ok/0132_box_expr.rs
  crates/parser/test_data/parser/inline/ok/0207_builtin_expr.rast
  crates/parser/test_data/parser/inline/ok/0207_builtin_expr.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
  crates/syntax/src/ast/prec.rs
  crates/syntax/src/tests/ast_src.rs
  crates/syntax/src/tests/sourcegen_ast.rs
Labels: S-waiting-on-review

#15556 minor: Update notify to 6.1.1
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/tests/slow-tests/tidy.rs
  crates/vfs-notify/Cargo.toml
Labels: S-waiting-on-review

#15559 Implement builtin#format_args, using rustc's format_args parser
  Cargo.lock
  crates/hir-def/Cargo.toml
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/body/tests.rs
  crates/hir-def/src/hir.rs
  crates/hir-def/src/hir/format_args.rs
  crates/hir-def/src/hir/format_args/parse.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/lang_item.rs
  crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
  crates/hir-def/src/macro_expansion_tests/mbe.rs
  crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
  crates/hir-def/src/path.rs
  crates/hir-def/src/pretty.rs
  crates/hir-def/src/resolver.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/name.rs
  crates/hir-ty/src/infer/path.rs
  crates/hir-ty/src/tests/simple.rs
  crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
  crates/ide-assists/src/tests/generated.rs
  crates/ide-completion/src/completions/format_string.rs
  crates/ide-db/src/syntax_helpers/format_string.rs
  crates/ide-diagnostics/src/handlers/macro_error.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/ide/src/syntax_highlighting/format.rs
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/tests.rs
  crates/parser/src/grammar/expressions/atom.rs
  crates/parser/src/syntax_kind/generated.rs
  crates/parser/test_data/parser/inline/ok/0207_builtin_expr.rast
  crates/parser/test_data/parser/inline/ok/0207_builtin_expr.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
  crates/syntax/src/tests/ast_src.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15564 internal: use current folder's `rustfmt.toml` with all rustfmt configurations
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/from_proto.rs
Labels: S-waiting-on-review

#15565 Implement `write_via_move` intrinsic for mir-eval
  crates/hir-ty/src/consteval/tests/intrinsics.rs
  crates/hir-ty/src/mir/eval/shim.rs
Labels: S-waiting-on-review

#15532 On type format '(', by adding closing ')' automatically
  crates/ide/src/typing.rs
  crates/rust-analyzer/src/caps.rs
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-review

#15567 Ignore enum variants in analysis stats of mir bodies
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-review

#15568 Replace format-args parser with upstream fork
  Cargo.lock
  Cargo.toml
  crates/hir-def/Cargo.toml
  crates/hir-def/src/hir/format_args.rs
  crates/hir-def/src/hir/format_args/parse.rs
  crates/hir-ty/Cargo.toml
Labels: S-waiting-on-review

#15571 Remove allocation on mir eval memory write
  crates/hir-ty/src/mir/eval.rs
Labels: S-waiting-on-review

#15574 minor : use crate name for `CARGO_CRATE_NAME`
  crates/project-model/src/workspace.rs
  crates/project-model/test_data/output/cargo_hello_world_project_model.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt
Labels: S-waiting-on-review

#15573 assist : `into_to_qualified_from`
  crates/ide-assists/src/handlers/into_to_qualified_from.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15558 code: remove `rust-analyzer.discoverProjectCommand` in favor of a companion extension
  editors/code/package.json
  editors/code/src/commands.ts
  editors/code/src/config.ts
  editors/code/src/ctx.ts
  editors/code/src/util.ts
Labels: S-waiting-on-review

#15430 minor : Deunwrap wrap_return_type_in_result
  crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
Labels: S-waiting-on-review

#15524 Bind unused parameter assistant
  crates/ide-assists/src/handlers/bind_unused_param.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15575 Intern projections in mir place
  crates/hir-ty/src/mir.rs
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/lower/as_place.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/hir-ty/src/mir/pretty.rs
Labels: S-waiting-on-review

#15529 Do not send inlay hint refresh requests on file edits
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#15528 Enable `rust_analyzer` for cfgs when code is being analyzed by rust-analyzer
  crates/base-db/src/fixture.rs
  crates/cfg/src/lib.rs
  crates/ide-completion/src/completions/attribute/cfg.rs
  crates/ide-completion/src/tests/attribute.rs
  crates/ide-db/src/search.rs
  crates/project-model/src/workspace.rs
  crates/project-model/test_data/output/cargo_hello_world_project_model.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt
  crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
Labels: S-waiting-on-review

#15522 Resolve inlay hint data
  crates/ide/src/inlay_hints.rs
  crates/ide/src/inlay_hints/adjustment.rs
  crates/ide/src/inlay_hints/bind_pat.rs
  crates/ide/src/inlay_hints/binding_mode.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/ide/src/inlay_hints/closing_brace.rs
  crates/ide/src/inlay_hints/closure_captures.rs
  crates/ide/src/inlay_hints/closure_ret.rs
  crates/ide/src/inlay_hints/discriminant.rs
  crates/ide/src/inlay_hints/fn_lifetime_fn.rs
  crates/ide/src/inlay_hints/implicit_static.rs
  crates/ide/src/inlay_hints/param_name.rs
  crates/ide/src/lib.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/vfs/src/lib.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#15577 Clear native diagnostics on file closing
  crates/rust-analyzer/src/handlers/notification.rs
Labels: S-waiting-on-review

#15578 Diagnose mismatched arg count for tuple struct patterns
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
  crates/ide-diagnostics/src/lib.rs
Labels: S-waiting-on-review

#15560 project-model: when using `rust-project.json`, prefer the sysroot-defined rustc over discovery in `$PATH`
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-author

#15584 Diagnose private fields in record constructor
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/data/adt.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir-ty/src/mir.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
  crates/ide-diagnostics/src/handlers/no_such_field.rs
Labels: S-waiting-on-review

#15586 shrink_to_fit body source map
  crates/hir-def/src/body.rs
  crates/hir-def/src/import_map.rs
Labels: S-waiting-on-review

#15592 Shrink some stuff
  crates/hir-ty/src/layout.rs
  crates/hir-ty/src/layout/adt.rs
  crates/hir-ty/src/layout/tests.rs
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/ide/src/status.rs
Labels: S-waiting-on-review

#15232 ide : Disallow renaming of non-local items
  crates/ide-db/src/rename.rs
  crates/ide/src/rename.rs
Labels: S-waiting-on-author

#15431 minor : Deunwrap extract_function
  crates/ide-assists/src/handlers/extract_function.rs
Labels: S-waiting-on-author

#15601 fix: Temporarily skip decl check in derive expansions
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/lib.rs
Labels: S-waiting-on-review

#15606 fix: Fix lens location "above_whole_item" breaking lenses
  crates/ide-db/src/search.rs
  crates/ide/src/annotations.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#15609 internal: Remove most of the duplication from `Semantics{,Impl}` via deref
  crates/hir/src/semantics.rs
Labels: S-waiting-on-review

#15611 Prefer stable paths over unstable ones in import path calculation
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/import_map.rs
Labels: S-waiting-on-review

#15597 Field shorthand overwritten in promote local to const assist
  crates/ide-assists/src/handlers/promote_local_to_const.rs
Labels: S-waiting-on-review

#15625 fix: Don't skip closure captures after let-else
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/layout/tests/closure.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
Labels: S-waiting-on-review

#15628 minor: Sync from downstream
  crates/hir-def/src/attr/builtin.rs
  crates/ide-db/src/generated/lints.rs
Labels: S-waiting-on-review, S-waiting-on-author, has-merge-commits

#15632 scip: Use load_workspace_at.
  crates/rust-analyzer/src/cli/scip.rs
Labels: S-waiting-on-review

#15616 Switch to in-tree rustc dependencies with a cfg flag
  Cargo.lock
  Cargo.toml
  crates/hir-def/Cargo.toml
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/hir/format_args.rs
  crates/hir-def/src/lib.rs
  crates/hir-ty/Cargo.toml
  crates/hir-ty/src/layout.rs
  crates/parser/Cargo.toml
  crates/parser/src/lexed_str.rs
  crates/parser/src/lib.rs
  crates/rust-analyzer/Cargo.toml
  crates/rustc-dependencies/Cargo.toml
  crates/rustc-dependencies/src/lib.rs
  crates/syntax/Cargo.toml
  crates/syntax/src/ast/token_ext.rs
  crates/syntax/src/lib.rs
  crates/syntax/src/validation.rs
Labels: S-waiting-on-review

#15635 Do not resolve inlayHint.textEdit for VSCode client
  crates/rust-analyzer/src/bin/main.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/diagnostics/to_proto.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
Labels: S-waiting-on-review

#15637 Update chalk version
  Cargo.lock
  crates/hir-ty/Cargo.toml
Labels: S-waiting-on-review

#15651 fix: Fix inlining closures from local variables and functions
  crates/ide-assists/src/handlers/inline_call.rs
  crates/ide-assists/src/handlers/inline_local_variable.rs
Labels: S-waiting-on-review

#15649 Documentation: Add parenthesis to the list of on-typing assists.
  crates/ide/src/typing.rs
Labels: S-waiting-on-review

#15615 Refactor/fix clippy lints
  crates/intern/src/lib.rs
  crates/parser/src/shortcuts.rs
  crates/syntax/src/ast/edit_in_place.rs
  crates/syntax/src/ast/make.rs
  crates/syntax/src/lib.rs
  crates/syntax/src/tests.rs
Labels: S-waiting-on-review

#15432 minor : Deunwrap inline call
  crates/ide-assists/src/handlers/inline_call.rs
Labels: S-waiting-on-review

#15587 Fix autoimport does nothing when importing trait that is as _ imports
  crates/ide-db/src/imports/insert_use/tests.rs
  crates/ide-db/src/imports/merge_imports.rs
Labels: S-waiting-on-review

#15620 triagebot exclude_labels -> exclude_titles
  triagebot.toml
Labels: S-waiting-on-review

#15652 minor: Various small fixes
  crates/hir-def/src/body/scope.rs
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/lib.rs
  crates/hir/src/source_analyzer.rs
  crates/stdx/src/macros.rs
  crates/stdx/src/process.rs
Labels: S-waiting-on-review

#15594 Deunwrap add_missing_match_arms
  crates/ide-assists/src/handlers/add_missing_match_arms.rs
Labels: S-waiting-on-author

#15425 minor : Deunwrap convert_comment_block and desugar_doc_comment
  crates/ide-assists/src/handlers/convert_comment_block.rs
  crates/ide-assists/src/handlers/desugar_doc_comment.rs
Labels: S-waiting-on-author

#15492 extend check.overrideCommand and buildScripts.overrideCommand docs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#15582 add option to show full function signatures in completion docs
  crates/ide-completion/src/config.rs
  crates/ide-completion/src/render/function.rs
  crates/ide-completion/src/tests.rs
  crates/ide-completion/src/tests/special.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#15660 minor: hover_simple refactor
  crates/base-db/src/input.rs
  crates/ide-db/src/defs.rs
  crates/ide/src/hover.rs
Labels: S-waiting-on-review

#15659 Add `unused_variables` native diagnostic
  crates/hir-ty/src/layout/tests/closure.rs
  crates/hir-ty/src/mir.rs
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/monomorphization.rs
  crates/hir-ty/src/mir/pretty.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/field_shorthand.rs
  crates/ide-diagnostics/src/handlers/incorrect_case.rs
  crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
  crates/ide-diagnostics/src/handlers/missing_unsafe.rs
  crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/ide-diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/ide-diagnostics/src/handlers/typed_hole.rs
  crates/ide-diagnostics/src/handlers/unused_variables.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15665 internal: De-`unwrap` `generate_function.rs`
  crates/ide-assists/src/handlers/generate_function.rs
Labels: S-waiting-on-review

#15669 Simplify
  crates/syntax/src/lib.rs
Labels: S-waiting-on-review

#15663 minor: update libc to 0.2.148
  Cargo.lock
Labels: S-waiting-on-review

#15662 fix: panic with wrapping/unwrapping result return type assists
  crates/ide-assists/src/handlers/unwrap_result_return_type.rs
  crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
Labels: S-waiting-on-review

#15672 Improve useRustcErrorCode description
  editors/code/package.json
Labels: S-waiting-on-review

#15677 Allocate ast ids for parameters
  crates/hir-def/src/data.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-expand/src/ast_id_map.rs
Labels: S-waiting-on-review

#15633 scip: Allow customizing cargo config.
  crates/rust-analyzer/src/cli/flags.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/rust-analyzer/src/config.rs
Labels: S-waiting-on-author

#15667 fix: make bool_to_enum assist create enum at top-level
  crates/ide-assists/src/handlers/bool_to_enum.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-author

#15682 Recover better on missing parameter in param list
  crates/parser/src/grammar/params.rs
  crates/parser/test_data/parser/inline/err/0023_empty_param_slot.rast
  crates/parser/test_data/parser/inline/err/0023_empty_param_slot.rs
Labels: S-waiting-on-review

#15686 Only run tests on linux in pull requests
  .github/workflows/ci.yaml
Labels: S-waiting-on-review

#15680 internal: re-generate lints.rs
  crates/ide-completion/src/item.rs
  crates/ide-db/src/generated/lints.rs
  crates/ide-db/src/tests/sourcegen_lints.rs
  crates/ide/src/hover/tests.rs
  crates/rust-analyzer/tests/slow-tests/tidy.rs
Labels: S-waiting-on-author

#15688 Make rustc_layout_scalar_valid_range attributes work for non-decimal literals
  crates/hir-ty/src/layout/adt.rs
Labels: S-waiting-on-review

#15692 fix: Typing underscore should not trigger completions in types or patterns
  crates/ide-completion/src/lib.rs
  crates/ide-completion/src/tests/special.rs
Labels: S-waiting-on-review

#15693 Downgrade `unused_variables` to experimental
  crates/ide-diagnostics/src/handlers/unused_variables.rs
Labels: S-waiting-on-review
