Repository rust-lang/rust-analyzer, pull requests merged in 2023-06, with the labels that each got.

#14938 feat: Add signature help for tuple patterns and expressions
  crates/hir-def/src/body/lower.rs
  crates/ide/src/signature_help.rs
  crates/parser/src/grammar/expressions/atom.rs
  crates/parser/src/grammar/patterns.rs
  crates/parser/test_data/parser/inline/err/0019_tuple_expr_leading_comma.rast
  crates/parser/test_data/parser/inline/err/0019_tuple_expr_leading_comma.rs
  crates/parser/test_data/parser/inline/err/0020_tuple_pat_leading_comma.rast
  crates/parser/test_data/parser/inline/err/0020_tuple_pat_leading_comma.rs
Labels: S-waiting-on-review

#14942 fix bug in labeled for loop desugaring
  crates/hir-def/src/body/lower.rs
  crates/ide-diagnostics/src/handlers/undeclared_label.rs
Labels: S-waiting-on-review

#14941 Shrink `DefMap`, share crate level items with block def maps
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/tests/block.rs
  crates/hir-def/src/child_by_source.rs
  crates/hir-def/src/db.rs
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/macro_expansion_tests/mod.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/attr_resolution.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/path_resolution.rs
  crates/hir-def/src/nameres/tests/macros.rs
  crates/hir-def/src/resolver.rs
  crates/hir-def/src/test_db.rs
  crates/hir-ty/src/display.rs
  crates/hir/src/display.rs
  crates/hir/src/lib.rs
  crates/ide-completion/src/completions.rs
  crates/ide-db/src/helpers.rs
  crates/ide-db/src/rename.rs
  crates/ide-db/src/search.rs
  crates/ide-diagnostics/src/handlers/unlinked_file.rs
  crates/ide/src/status.rs
  crates/ide/src/syntax_highlighting/highlight.rs
  lib/la-arena/src/lib.rs
Labels: S-waiting-on-review

#14947 Add enum, reference, array and slice to `render_const_scalar`
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/lib.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#14945 Fix Assist "replace named generic type with impl trait"
  crates/ide-assists/src/handlers/replace_named_generic_with_impl.rs
Labels: S-waiting-on-review

#14950 Support floating point intrinsics in const eval
  crates/hir-ty/src/consteval/tests/intrinsics.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#14951 Fix string pattern matching in mir interpreter
  crates/hir-ty/src/chalk_ext.rs
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/hir-ty/src/mir/eval/tests.rs
  crates/hir-ty/src/mir/lower.rs
Labels: S-waiting-on-review

#14952 fix: assignment operators are right associative
  crates/parser/src/grammar/expressions.rs
  crates/parser/test_data/parser/ok/0028_operator_binding_power.rast
  crates/parser/test_data/parser/ok/0028_operator_binding_power.rs
  crates/parser/test_data/parser/ok/0072_destructuring_assignment.rast
  crates/parser/test_data/parser/ok/0072_destructuring_assignment.rs
Labels: S-waiting-on-review

#14955 Remove unnecessary `StorageDead`
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/hir-ty/src/utils.rs
Labels: S-waiting-on-review

#14961 Fix drop scopes problems in mir
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/tests.rs
  crates/hir-ty/src/mir/lower.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#14965 Add mandatory panic contexts to all threadpool tasks
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/src/task_pool.rs
Labels: S-waiting-on-review

#14967 Revert "Add mandatory panic contexts to all threadpool tasks"
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/src/task_pool.rs
Labels: S-waiting-on-review

#14969 Update builtin attribute list
  Cargo.toml
  crates/hir-def/src/attr/builtin.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#14970 Detect "bound more than once" error and suppress `need-mut` for it.
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/hir.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
Labels: S-waiting-on-review

#14972 Fix `unused-mut` false positive for `Box`
  crates/hir-ty/src/mir/borrowck.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
Labels: S-waiting-on-review

#14976 Fix missing terminator for slice pattern
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
Labels: S-waiting-on-review

#14971 fix: consider outer binders when folding captured items' type
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/mir/eval/tests.rs
  crates/hir-ty/src/mir/monomorphization.rs
Labels: S-waiting-on-review

#14978 Emit `'_` for lifetime generics in `HirDisplay`
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/tests/patterns.rs
  crates/hir-ty/src/tests/regression.rs
  crates/ide-assists/src/handlers/extract_function.rs
Labels: S-waiting-on-review

#14980 Sync from downstream
  crates/hir-def/src/attr/builtin.rs
  crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/proc-macro-api/src/version.rs
  crates/proc-macro-srv/src/server.rs
Labels: S-waiting-on-review

#14984 internal: Bring back sysroot-abi feature
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
Labels: S-waiting-on-review

#14994 fix: Fix ci never running on nightly when proc-macro things change
  .github/workflows/ci.yaml
Labels: S-waiting-on-review

#14925 feat: inline const as literal
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/inline_const_as_literal.rs
  crates/ide-assists/src/handlers/raw_string.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#14995 fix: Fix proc-macro slow test
  .github/workflows/ci.yaml
  crates/rust-analyzer/tests/slow-tests/main.rs
Labels: S-waiting-on-review

#15000 fix: only generate trait bound for associated types in field types
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-ty/src/tests/traits.rs
Labels: S-waiting-on-review

#15006 Fix unwrap on None in expanding format args
  crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
Labels: S-waiting-on-review

#14997 internal: Fix dependency warning
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
Labels: S-waiting-on-review

#15012 Infer return type for async function in `generate_function`
  crates/ide-assists/src/handlers/generate_function.rs
Labels: S-waiting-on-review

#14998 internal: Lazy eager macros
  crates/hir-def/src/expander.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/eager.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/proc_macro.rs
  crates/ide-db/src/test_data/test_doc_alias.txt
  crates/ide-db/src/test_data/test_symbol_index_collection.txt
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/tests.rs
Labels: S-waiting-on-review

#15014 Document the sysroot field in JsonProject
  docs/user/manual.adoc
Labels: S-waiting-on-review

#14979 internal: Migrate some assists to use the structured snippet API
  crates/ide-assists/src/handlers/add_missing_impl_members.rs
  crates/ide-assists/src/handlers/extract_type_alias.rs
  crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
  crates/ide-assists/src/utils.rs
  crates/syntax/src/ast/make.rs
Labels: S-waiting-on-review

#15019 Fix panic in displaying const trait objects
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/mir/eval.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#15020 Count query entries in memory usage command
  crates/hir-def/src/lib.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-ty/src/display.rs
  crates/ide-db/src/apply_change.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/cli.rs
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-review

#15022 Fix panic in displaying unsized structs
  crates/hir-ty/src/display.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#14960 Add span to group.
  crates/proc-macro-srv/src/server.rs
  crates/rust-analyzer/src/cli/diagnostics.rs
  crates/rust-analyzer/src/cli/flags.rs
Labels: S-waiting-on-review

#14827 autopublish: Offset version number
  .github/workflows/autopublish.yaml
Labels: S-waiting-on-review

#14875 fix: implemeted lifetime transformation fot assits
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/add_missing_impl_members.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-db/src/path_transform.rs
Labels: S-waiting-on-author

#14974 Properly format documentation for `SignatureHelpRequest`s
  crates/rust-analyzer/src/to_proto.rs
Labels: S-waiting-on-author

#14989 fix: derive source scope from syntax node to be transformed
  crates/hir/src/semantics.rs
  crates/ide-assists/src/handlers/add_missing_impl_members.rs
  crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
  crates/ide-assists/src/utils.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
Labels: S-waiting-on-review

#15025 minor: remove commented out conflicts
  crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
Labels: S-waiting-on-review

#15028 internal: Give rustfmt jobs a separate thread
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#15032 fix: exclude Markdown injection grammar from .vscodeignore.
  editors/code/.vscodeignore
Labels: S-waiting-on-review

#14932 Lower const params with a bad id
  crates/base-db/src/fixture.rs
  crates/base-db/src/input.rs
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/db.rs
  crates/hir-def/src/expander.rs
  crates/hir-def/src/hir.rs
  crates/hir-def/src/hir/type_ref.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/path.rs
  crates/hir-def/src/path/lower.rs
  crates/hir-def/src/resolver.rs
  crates/hir-expand/src/ast_id_map.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/consteval.rs
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/db.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/path.rs
  crates/hir-ty/src/interner.rs
  crates/hir-ty/src/layout/tests.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/pretty.rs
  crates/hir-ty/src/tests.rs
  crates/hir-ty/src/tests/regression.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/from_id.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/hir/src/source_analyzer.rs
  crates/hir/src/symbols.rs
  crates/ide-assists/src/handlers/extract_type_alias.rs
  crates/ide-db/src/search.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/parser/src/grammar/types.rs
  crates/parser/test_data/parser/inline/ok/0017_array_type.rast
  crates/parser/test_data/parser/ok/0030_traits.rast
  crates/parser/test_data/parser/ok/0043_complex_assignment.rast
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15040 fix: Use a more obscure hasher name in derive expansion
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-expand/src/builtin_derive_macro.rs
Labels: S-waiting-on-review

#15044 Deduplicate tuple indices for completion
  crates/ide-completion/src/completions/dot.rs
Labels: S-waiting-on-review

#15053 internal: Add a CrateRootModuleId that encodes a module id that is always a crate root
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/resolver.rs
  crates/hir-expand/src/ast_id_map.rs
  crates/hir/src/lib.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#15058 Add more log in "terminator is none" assert
  crates/hir-ty/src/mir/borrowck.rs
Labels: S-waiting-on-review

#15062 doc: remove duplicated words
  docs/user/manual.adoc
Labels: S-waiting-on-review

#14693 Support `Pointee` trait
  Cargo.lock
  crates/hir-ty/Cargo.toml
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/tests/simple.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/test-utils/src/fixture.rs
  crates/test-utils/src/minicore.rs
Labels: S-blocked

#15065 internal: Do not allocate unnecessarily when importing macros from parent modules
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/nameres/collector.rs
  crates/ide-assists/src/handlers/generate_delegate_methods.rs
  lib/la-arena/src/lib.rs
Labels: S-waiting-on-review

#15067 internal: Add more context to overly long loop turn message
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#15066 internal: Analyze all bodies in analysis-stats, not just functions
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/flags.rs
Labels: S-waiting-on-review

#15069 analysis-stats: Add body lowering step, track time of each step separtely
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/flags.rs
  crates/rust-analyzer/src/cli/progress_report.rs
Labels: S-waiting-on-review

#15054 fix: implement missing members doesn't transform const params and default types
  crates/ide-assists/src/handlers/add_missing_impl_members.rs
  crates/ide-assists/src/handlers/inline_call.rs
  crates/ide-db/src/path_transform.rs
Labels: S-waiting-on-review

#15075 fix: Add binding definition for for-expr iterator desugared binding
  crates/hir-def/src/body/lower.rs
  crates/hir/src/lib.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-review

#15076 internal: Shrink size of hir::Binding
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/hir.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/mir/lower.rs
Labels: S-waiting-on-review

#15087 internal: use consistent style for error handling
  crates/paths/src/lib.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/lib.rs
  crates/project-model/src/manifest_path.rs
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/target_data_layout.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/load_cargo.rs
  crates/rust-analyzer/src/cli/lsif.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/rust-analyzer/src/cli/ssr.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/reload.rs
  crates/vfs/src/vfs_path.rs
  docs/dev/style.md
  xtask/src/install.rs
  xtask/src/publish.rs
Labels: S-waiting-on-review

#15089 fix: Use RA_LOG in slow tests logging infra again
  crates/rust-analyzer/tests/slow-tests/support.rs
Labels: S-waiting-on-review

#15086 internal: Intern use and extern crate items like other items
  crates/hir-def/src/attr.rs
  crates/hir-def/src/data.rs
  crates/hir-def/src/db.rs
  crates/hir-def/src/dyn_map/keys.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/resolver.rs
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir/src/attrs.rs
Labels: S-waiting-on-review

#15074 Correctly handle inlining of async fn
  crates/ide-assists/src/handlers/inline_call.rs
  crates/syntax/src/ast/edit_in_place.rs
  crates/syntax/src/ast/make.rs
Labels: S-waiting-on-review

#15095 Change in-tree libs to workspace dependencies and bump versions
  Cargo.lock
  Cargo.toml
  crates/base-db/Cargo.toml
  crates/hir-def/Cargo.toml
  crates/hir-expand/Cargo.toml
  crates/hir-ty/Cargo.toml
  crates/profile/Cargo.toml
  crates/project-model/Cargo.toml
  crates/rust-analyzer/Cargo.toml
  lib/la-arena/Cargo.toml
  lib/lsp-server/Cargo.toml
Labels: S-waiting-on-review

#15097 Fix VfsPath Display and Debug impls
  crates/vfs/src/vfs_path.rs
Labels: S-waiting-on-review

#15070 internal: Report metric timings for file item trees and crate def map creation
  crates/hir-def/src/nameres.rs
  crates/hir/src/has_source.rs
  crates/ide-completion/src/completions/mod_.rs
  crates/ide-db/src/search.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/diagnostics.rs
Labels: S-waiting-on-review

#15098 Use lib crates from crates.io
  Cargo.lock
  Cargo.toml
  lib/README.md
Labels: S-waiting-on-review

#15102 Remove markdown injection for block comments
  editors/code/package.json
  editors/code/rustdoc.markdown.injection.tmGrammar.json
Labels: S-waiting-on-review

#15100 internal: Simplify `VfsPath` `fmt` impls
  crates/vfs/src/vfs_path.rs
Labels: S-waiting-on-review

#15104 Skip mutable diagnostics on synthetic bindings
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
Labels: S-waiting-on-review

#15077 Bump deps
  Cargo.lock
  Cargo.toml
  crates/cfg/Cargo.toml
  crates/flycheck/Cargo.toml
  crates/hir-def/Cargo.toml
  crates/hir-expand/Cargo.toml
  crates/hir/Cargo.toml
  crates/intern/Cargo.toml
  crates/proc-macro-api/Cargo.toml
  crates/proc-macro-srv/Cargo.toml
  crates/rust-analyzer/Cargo.toml
  crates/stdx/Cargo.toml
  crates/vfs-notify/Cargo.toml
  lib/line-index/Cargo.toml
  lib/lsp-server/Cargo.toml
Labels: S-waiting-on-review

#14948 feature : assist delegate impl
  crates/ide-assists/src/handlers/generate_delegate_trait.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-review

#15105 Change comparsion for checking if number is negative to include 128
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/mir/eval.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#15112 Support manual impl of fn traits in mir interpreter
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/consteval/tests/intrinsics.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
Labels: S-waiting-on-review

#15116 Remove markdown injection again
  editors/code/.vscodeignore
  editors/code/package.json
  editors/code/rustdoc.markdown.injection.tmGrammar.json
Labels: S-waiting-on-review

#15119 Support more intrinsics in mir interpreter
  crates/hir-ty/src/consteval/tests/intrinsics.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/hir-ty/src/mir/eval/shim/simd.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15120 minor: Neovim, not NeoVim
  docs/user/manual.adoc
Labels: S-waiting-on-review

#15126 Upgrade to indexmap v2
  Cargo.lock
  crates/hir-def/Cargo.toml
  crates/ide-db/Cargo.toml
  crates/syntax/Cargo.toml
  crates/vfs/Cargo.toml
Labels: S-waiting-on-review

#15135 Fix some unsizing problems in mir
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/layout/tests.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15140 Add the comment why `HasSource::source()` returns `Option`
  crates/hir/src/has_source.rs
Labels: S-waiting-on-review

#15142 internal: Rename crates after removing libs from workspace
  .github/workflows/autopublish.yaml
Labels: S-waiting-on-review

#15151 Update dependencies for editor/code
  editors/code/package-lock.json
  editors/code/package.json
Labels: S-waiting-on-review

#15153 Clean up `activationEvents` field in vscode extension's package.json
  editors/code/package.json
Labels: S-waiting-on-review

#15154 editor/code: Use `@tsconfig/strictest` to define type checking rules
  editors/code/package-lock.json
  editors/code/package.json
  editors/code/tsconfig.json
Labels: S-waiting-on-review

#15101 Check Workspace Edit ResourceOps
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
Labels: S-waiting-on-review

#15125 internal: support `#[rustc_coinductive]`
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/tests/traits.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15136 delete matching brace key binding
  editors/code/package.json
Labels: S-waiting-on-review

#15148 Fix `self` and `super` path resolution in block modules
  crates/hir-def/src/body/tests.rs
  crates/hir-def/src/body/tests/block.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/path_resolution.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#15030 ci(metrics): Run measurement functions in parallel
  .github/workflows/metrics.yaml
  xtask/src/flags.rs
  xtask/src/metrics.rs
Labels: S-waiting-on-review

#15161 internal: add `library` fixture meta
  crates/base-db/src/fixture.rs
  crates/base-db/src/input.rs
  crates/ide/src/moniker.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/test-utils/src/fixture.rs
Labels: S-waiting-on-review

#15163 fix(metrics): Push to master branch
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#15157 Fix runnable detection for `#[tokio::test]`
  crates/hir-def/src/attr.rs
  crates/ide/src/runnables.rs
Labels: S-waiting-on-review

#15138 13583 rename runnable env to runnables extra env
  docs/user/manual.adoc
  editors/code/package.json
  editors/code/src/config.ts
  editors/code/src/debug.ts
  editors/code/src/run.ts
Labels: S-waiting-on-review

#15172 Support #[derive_const(Trait)]
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-expand/src/builtin_attr_macro.rs
  crates/hir-expand/src/name.rs
  crates/ide-completion/src/tests/attribute.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#15173 Fix data layout of reference to nested unsized structs
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/layout.rs
  crates/hir-ty/src/layout/tests.rs
Labels: S-waiting-on-review

#15174 editor/code: Switch to `@vscode/vsce`
  editors/code/package-lock.json
  editors/code/package.json
Labels: S-waiting-on-review

#15175 internal: Drop `cross-env` npm dep
  editors/code/package-lock.json
  editors/code/package.json
  editors/code/tests/unit/settings.test.ts
Labels: S-waiting-on-review

#15177 Fix panic in `handle_code_action`
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-review

#15180 Purge of unwraps
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-review

#15169 Use anonymous lifetime where possible
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-expand/src/name.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/infer/coerce.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/mutability.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/traits.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/semantics.rs
  crates/ide-assists/src/handlers/pull_assignment_up.rs
  crates/ide-db/src/path_transform.rs
  crates/ide-db/src/search.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide-ssr/src/search.rs
  crates/mbe/src/expander/matcher.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/tt_iter.rs
  crates/parser/src/shortcuts.rs
  crates/profile/src/tree.rs
  crates/rust-analyzer/src/bin/logger.rs
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  crates/tt/src/buffer.rs
Labels: S-waiting-on-review

#15184 Disable mir interpreter for targets with different pointer size from host
  crates/hir-ty/src/mir/eval.rs
Labels: S-waiting-on-review

#15185 Bump chalk
  Cargo.lock
  crates/hir-ty/Cargo.toml
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/tests/macros.rs
  crates/hir-ty/src/tests/regression.rs
Labels: S-waiting-on-review
