Repository rust-lang/rust-analyzer, pull requests merged in 2024-03, with the labels that each got.

#16728 minor: Move span stuff around
  Cargo.lock
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/lower.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/files.rs
  crates/hir-expand/src/hygiene.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/mod_path.rs
  crates/span/Cargo.toml
  crates/span/src/ast_id.rs
  crates/span/src/hygiene.rs
  crates/span/src/lib.rs
Labels: S-waiting-on-review

#16727 fix: Don't highlight related assoc items of super traits
  crates/ide/src/highlight_related.rs
Labels: S-waiting-on-review

#16735 minor: Remove outdated comment about static SmolStrs
  crates/hir-expand/src/name.rs
Labels: S-waiting-on-review

#16704 internal: Simplify
  crates/flycheck/src/lib.rs
  crates/ide-assists/src/handlers/destructure_struct_binding.rs
  crates/ide-db/src/prime_caches.rs
  crates/proc-macro-srv/src/server.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers/notification.rs
  docs/user/generated_config.adoc
  editors/code/package.json
  lib/lsp-server/src/stdio.rs
Labels: S-waiting-on-review

#16702 fix: Ignore generic arguments in intra doc link path resolution
  Cargo.toml
  crates/hir/src/attrs.rs
  crates/ide-db/src/defs.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/doc_links/intra_doc_links.rs
  crates/ide/src/hover/tests.rs
  crates/syntax/fuzz/Cargo.toml
Labels: S-waiting-on-review

#16738 Update rustc_pattern_analysis
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#16719 fix: Add basic support for Native Debug
  editors/code/src/debug.ts
Labels: S-waiting-on-review

#16723 fix: autocomplete constants inside format strings
  crates/ide-completion/src/completions/format_string.rs
Labels: S-waiting-on-review

#16690 fix: use 4 spaces for indentation in macro expansion
  crates/ide-assists/src/handlers/inline_call.rs
  crates/ide-assists/src/handlers/inline_macro.rs
  crates/ide-db/src/syntax_helpers/insert_whitespace_into_node.rs
  crates/ide/src/expand_macro.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#16703 Add more methods for resolving definitions from AST to their corresponding HIR types
  crates/hir/src/semantics.rs
  crates/hir/src/semantics/source_to_def.rs
  crates/ide-assists/src/handlers/generate_delegate_trait.rs
  crates/ide-assists/src/handlers/move_from_mod_rs.rs
  crates/ide-assists/src/handlers/move_to_mod_rs.rs
  crates/ide-db/src/helpers.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide/src/parent_module.rs
  crates/ide/src/rename.rs
  crates/ide/src/runnables.rs
  crates/ide/src/syntax_highlighting.rs
Labels: S-waiting-on-review

#16747 internal: Clean some stuff up
  Cargo.lock
  crates/base-db/Cargo.toml
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/diagnostics.rs
  crates/hir-def/src/nameres/mod_resolution.rs
  crates/hir-def/src/nameres/path_resolution.rs
  crates/hir-expand/Cargo.toml
  crates/hir-expand/src/builtin_attr_macro.rs
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/change.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-ty/Cargo.toml
  crates/hir/Cargo.toml
  crates/hir/src/lib.rs
  crates/ide-assists/Cargo.toml
  crates/ide-completion/Cargo.toml
  crates/ide-db/src/apply_change.rs
  crates/ide-db/src/lib.rs
  crates/ide-diagnostics/Cargo.toml
  crates/ide/src/lib.rs
  crates/load-cargo/src/lib.rs
  crates/parser/Cargo.toml
  crates/parser/src/lexed_str.rs
  crates/parser/src/lib.rs
  crates/parser/src/shortcuts.rs
  crates/proc-macro-api/Cargo.toml
  crates/profile/src/lib.rs
  crates/project-model/Cargo.toml
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/rust-analyzer/src/reload.rs
  crates/syntax/Cargo.toml
  crates/syntax/src/lib.rs
  crates/syntax/src/parsing.rs
  crates/syntax/src/validation.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#16748 internal: Compute syntax validation errors on demand
  crates/hir-def/src/data.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/diagnostics.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/files.rs
  crates/ide-diagnostics/src/lib.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/rust-analyzer/src/tracing/hprof.rs
  crates/syntax/src/lib.rs
  crates/syntax/src/tests.rs
  crates/syntax/src/validation.rs
Labels: S-waiting-on-review

#16750 minor: Mark remove_unnecessary_else as experimental
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
Labels: S-waiting-on-review

#16708 internal: Move ide-assists codegen tests into an xtask codegen command
  .cargo/config.toml
  .github/workflows/ci.yaml
  Cargo.lock
  crates/ide-assists/Cargo.toml
  crates/ide-assists/src/tests.rs
  xtask/Cargo.toml
  xtask/src/codegen.rs
  xtask/src/codegen/assists_doc_tests.rs
  xtask/src/flags.rs
  xtask/src/main.rs
  xtask/src/release.rs
Labels: S-waiting-on-review

#16751 internal: Move diagnostics docs generation and lint definition generation into xtask/codegen
  Cargo.lock
  crates/ide-assists/Cargo.toml
  crates/ide-db/Cargo.toml
  crates/ide-db/src/generated/lints.rs
  crates/ide-db/src/lib.rs
  crates/ide-db/src/tests/line_index.rs
  crates/ide-diagnostics/Cargo.toml
  crates/ide-diagnostics/src/tests.rs
  crates/ide/Cargo.toml
  crates/ide/src/hover/tests.rs
  crates/rust-analyzer/Cargo.toml
  lib/line-index/Cargo.toml
  lib/line-index/src/tests.rs
  xtask/src/codegen.rs
  xtask/src/codegen/diagnostics_docs.rs
  xtask/src/codegen/lints.rs
  xtask/src/flags.rs
  xtask/src/release.rs
Labels: S-waiting-on-review

#15938 feat: add hover display for trait assoc items
  crates/hir-ty/src/display.rs
  crates/hir/src/display.rs
  crates/ide/src/hover.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#16756 internal: Adjust a few things for trait assoc item hovers
  crates/hir-ty/src/display.rs
  crates/hir/src/display.rs
  crates/ide/src/hover.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/config.rs
Labels: S-waiting-on-review

#16757 fix: Put style lints behind disabled-by-default config
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/lib.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#16758 Update Cargo.lock
  Cargo.lock
  Cargo.toml
  crates/ide-db/src/prime_caches.rs
  crates/ide/Cargo.toml
  crates/proc-macro-api/Cargo.toml
  crates/proc-macro-srv/Cargo.toml
  crates/salsa/Cargo.toml
  crates/salsa/src/runtime.rs
  crates/salsa/tests/cycles.rs
  crates/salsa/tests/parallel/parallel_cycle_all_recover.rs
  crates/salsa/tests/parallel/parallel_cycle_mid_recover.rs
  crates/salsa/tests/parallel/parallel_cycle_none_recover.rs
  crates/salsa/tests/parallel/parallel_cycle_one_recovers.rs
Labels: S-waiting-on-review

#16761 minor: remove `ignore-hidden = false`
  .typos.toml
Labels: S-waiting-on-review

#16759 fix: goto-definition for constants inside range pattern
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/hir.rs
  crates/hir-ty/src/mir/lower.rs
  crates/ide/src/goto_definition.rs
Labels: S-waiting-on-review

#16763 Add `fn index()` and `fn parent_fn()` accessors for `hir::Param`/`hir::SelfParam`
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#16662 Add test explorer
  Cargo.toml
  crates/flycheck/src/command.rs
  crates/flycheck/src/lib.rs
  crates/flycheck/src/test_runner.rs
  crates/ide/src/lib.rs
  crates/ide/src/test_explorer.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/hack_recover_crate_name.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lib.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/stdx/src/process.rs
  docs/dev/lsp-extensions.md
  editors/code/src/ctx.ts
  editors/code/src/lsp_ext.ts
  editors/code/src/test_explorer.ts
Labels: S-waiting-on-review

#16766 fix: keep attributes in assist 'generate_delegate_trait'
  crates/ide-assists/src/handlers/generate_delegate_trait.rs
Labels: S-waiting-on-review

#16769 fix: Function argument type inference with associated type impl trait
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/tests/traits.rs
Labels: S-waiting-on-review

#16755 For toolchain binaries use the full path found in $PATH
  Cargo.lock
  crates/ide/src/expand_macro.rs
  crates/proc-macro-srv/proc-macro-test/Cargo.toml
  crates/proc-macro-srv/proc-macro-test/build.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/target_data_layout.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/toolchain/src/lib.rs
Labels: S-waiting-on-review

#16770 fix: panic when using float numbers without dots in chain calls
  crates/parser/src/shortcuts.rs
  crates/parser/test_data/parser/err/0054_float_split_scientific_notation.rast
  crates/parser/test_data/parser/err/0054_float_split_scientific_notation.rs
Labels: S-waiting-on-review

#16773 fix: Add config and capability for test explorer
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/dev/lsp-extensions.md
  editors/code/package.json
  editors/code/src/client.ts
  editors/code/src/config.ts
  editors/code/src/ctx.ts
Labels: S-waiting-on-review

#16772 internal: Add tracing spans to macro generated database
  crates/base-db/src/lib.rs
  crates/hir-def/src/attr.rs
  crates/hir-def/src/db.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-ty/src/db.rs
  crates/hir/src/db.rs
  crates/ide-db/src/apply_change.rs
  crates/ide-db/src/lib.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/rust-analyzer/src/tracing/config.rs
  crates/rust-analyzer/src/tracing/hprof.rs
  crates/salsa/salsa-macros/src/query_group.rs
  crates/salsa/src/derived.rs
  crates/salsa/tests/cycles.rs
  crates/salsa/tests/on_demand_inputs.rs
  crates/salsa/tests/parallel/parallel_cycle_none_recover.rs
Labels: S-waiting-on-review

#16775 fix: Remove accidental dependency between `parse_macro_expansion` and `parse`
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/span_map.rs
Labels: S-waiting-on-review

#16776 fix: Don't force draw a dependency edge to the real_span_map query
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/expander.rs
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/hir/type_ref.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/lower.rs
  crates/hir-def/src/visibility.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-expand/src/eager.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-ty/src/display.rs
  crates/hir/src/semantics.rs
  crates/hir/src/source_analyzer.rs
  crates/span/src/ast_id.rs
Labels: S-waiting-on-review

#16777 fix: Don't invalid body query results when generating desugared names
  crates/hir-def/src/body/lower.rs
  crates/hir-expand/src/name.rs
Labels: S-waiting-on-review

#16778 Update `rustc_pattern_analysis` to 0.42.0
  Cargo.lock
  Cargo.toml
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
  crates/hir-ty/src/layout.rs
Labels: S-waiting-on-review

#16779 minor: Skip match diagnostics for partially unknown types
  crates/hir-ty/src/diagnostics/expr.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Labels: S-waiting-on-review

#16781 fix: Don't escape `\` and `$` in "Extract format expressions" assist
  crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
  crates/ide-db/src/syntax_helpers/format_string_exprs.rs
Labels: S-waiting-on-review

#16782 fix: Preserve $ and \ in postfix format completions
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/completions/postfix/format_like.rs
  crates/ide-db/src/syntax_helpers/format_string_exprs.rs
Labels: S-waiting-on-review

#16785 internal: Remove unused keyword from visibility recovery
  crates/parser/src/grammar.rs
Labels: S-waiting-on-review

#16786 internal: Improve readability of the parser code
  crates/parser/src/grammar.rs
  crates/parser/src/grammar/expressions.rs
  crates/parser/src/grammar/expressions/atom.rs
  crates/parser/src/grammar/generic_params.rs
  crates/parser/src/grammar/items.rs
  crates/parser/src/grammar/items/traits.rs
  crates/parser/src/grammar/params.rs
  crates/parser/src/grammar/patterns.rs
  crates/parser/src/grammar/types.rs
  crates/parser/src/parser.rs
Labels: S-waiting-on-review

#16787 Remove unncessary check for macro call
  crates/parser/src/grammar/items.rs
Labels: S-waiting-on-review

#16795 remove unused struct Snap in lsif
  crates/rust-analyzer/src/cli/lsif.rs
Labels: S-waiting-on-review

#16794 Some minor changes in the test explorer lsp extension
  crates/flycheck/src/test_runner.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/dev/lsp-extensions.md
  editors/code/src/lsp_ext.ts
  editors/code/src/test_explorer.ts
Labels: S-waiting-on-review

#16807 minor: sync last two releases from downstream
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/ide/Cargo.toml
  crates/load-cargo/src/lib.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
Labels: S-waiting-on-review, S-waiting-on-author, has-merge-commits

#16784 internal: Remove synstructure const hack support
  crates/hir-def/src/child_by_source.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/src.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/tests/method_resolution.rs
  crates/hir/src/lib.rs
  crates/hir/src/symbols.rs
  crates/ide/src/navigation_target.rs
Labels: S-waiting-on-review

#16749 internal: Some method resolution cleanups
  Cargo.toml
  crates/hir-ty/Cargo.toml
  crates/hir-ty/src/autoderef.rs
  crates/hir-ty/src/infer/coerce.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/path.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/tests/method_resolution.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#16762 Added QuickFix for unresolved field.
  crates/ide-diagnostics/src/handlers/unresolved_field.rs
Labels: S-waiting-on-author

#16473 Stop eagerly resolving inlay hint text edits for VSCode
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/bin/main.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/diagnostics/to_proto.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
Labels: S-blocked

#16771 internal: Don't desugar self param into a pattern
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/body/scope.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/layout.rs
  crates/hir-ty/src/mir.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/hir-ty/src/tests.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics/source_to_def.rs
  crates/hir/src/source_analyzer.rs
  crates/ide/src/inlay_hints/implicit_drop.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#16810 feat: add fix for unused_variables
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/ide-diagnostics/src/handlers/unused_variables.rs
Labels: S-waiting-on-review

#16808 feat: Add proc macro semantic token type
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/ide-completion/src/item.rs
  crates/ide-db/src/lib.rs
  crates/ide/src/references.rs
  crates/ide/src/syntax_highlighting.rs
  crates/ide/src/syntax_highlighting/html.rs
  crates/ide/src/syntax_highlighting/tags.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
  crates/ide/src/syntax_highlighting/test_data/highlight_attributes.html
  crates/ide/src/syntax_highlighting/test_data/highlight_block_mod_items.html
  crates/ide/src/syntax_highlighting/test_data/highlight_crate_root.html
  crates/ide/src/syntax_highlighting/test_data/highlight_default_library.html
  crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
  crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
  crates/ide/src/syntax_highlighting/test_data/highlight_general.html
  crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
  crates/ide/src/syntax_highlighting/test_data/highlight_keywords.html
  crates/ide/src/syntax_highlighting/test_data/highlight_lifetimes.html
  crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
  crates/ide/src/syntax_highlighting/test_data/highlight_module_docs_inline.html
  crates/ide/src/syntax_highlighting/test_data/highlight_module_docs_outline.html
  crates/ide/src/syntax_highlighting/test_data/highlight_operators.html
  crates/ide/src/syntax_highlighting/test_data/highlight_rainbow.html
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
  crates/rust-analyzer/src/lsp/semantic_tokens.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#16335 internal: Compress file text using LZ4
  Cargo.lock
  crates/base-db/Cargo.toml
  crates/base-db/src/change.rs
  crates/base-db/src/lib.rs
  crates/hir-def/src/nameres/tests/incremental.rs
  crates/hir-expand/src/change.rs
  crates/hir-ty/src/tests.rs
  crates/hir-ty/src/tests/incremental.rs
  crates/ide-db/src/apply_change.rs
  crates/ide-db/src/lib.rs
  crates/ide/src/lib.rs
  crates/load-cargo/src/lib.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-author

#16811 fix: Fix method resolution snapshotting receiver_ty too early
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/method_resolution.rs
  crates/ide-diagnostics/src/handlers/unresolved_field.rs
Labels: S-waiting-on-review

#16789 feat: Configure derive macro inputs
  crates/cfg/Cargo.toml
  crates/cfg/src/cfg_expr.rs
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-expand/src/cfg_process.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/fixup.rs
  crates/hir-expand/src/lib.rs
  crates/mbe/src/syntax_bridge.rs
Labels: S-waiting-on-review

#16820 fix: Don't auto-close block comments in strings
  editors/code/language-configuration.json
Labels: S-waiting-on-review

#16824 minor: Fix unwanted leading whitespace in hover text
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#16832 internal: Shrink MacroCallLoc
  crates/hir-def/src/data.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/nameres/attr_resolution.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/builtin_attr_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/eager.rs
  crates/hir-expand/src/lib.rs
Labels: S-waiting-on-review

#16834 feat: Support macro calls in eager macros for IDE features
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/db.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/item_tree/tests.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/mbe.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/quote.rs
  crates/hir-expand/src/span_map.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/ide-completion/src/completions/env_vars.rs
  crates/ide-completion/src/lib.rs
  crates/ide/src/goto_definition.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
  crates/proc-macro-srv/src/tests/mod.rs
  crates/proc-macro-srv/src/tests/utils.rs
  crates/span/src/hygiene.rs
  crates/span/src/lib.rs
  crates/span/src/map.rs
  crates/stdx/src/anymap.rs
  crates/tt/src/lib.rs
Labels: S-waiting-on-review

#16841 internal: Use assoc items as anchors for spans
  crates/hir-expand/src/span_map.rs
  crates/ide-db/src/defs.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/syntax/src/ast/node_ext.rs
Labels: S-waiting-on-review

#16842 internal: Make def site span for proc-macro more invalidation resistant
  crates/hir-def/src/db.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/item_tree/tests.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/lib.rs
Labels: S-waiting-on-review

#16844 internal: Replace `Span` with `SyntaxContextId` in `MacroCallLoc`
  crates/hir-def/src/data.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/item_tree/tests.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/mbe/matching.rs
  crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs
  crates/hir-def/src/nameres/attr_resolution.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-expand/src/builtin_attr_macro.rs
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-expand/src/eager.rs
  crates/hir-expand/src/fixup.rs
  crates/hir-expand/src/hygiene.rs
  crates/hir-expand/src/lib.rs
  crates/hir/src/semantics.rs
  crates/mbe/src/benchmark.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/syntax_bridge/tests.rs
  crates/span/src/lib.rs
Labels: S-waiting-on-review

#16845 Show compilation progress in test explorer
  crates/flycheck/src/test_runner.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/dev/lsp-extensions.md
  editors/code/src/lsp_ext.ts
  editors/code/src/test_explorer.ts
Labels: S-waiting-on-review

#16847 Distinguish integration tests from crates in test explorer
  crates/ide/src/test_explorer.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#16851 internal: Build releases on Ubuntu 20.04
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16856 fix: Fix wrong where clause rendering on hover
  crates/hir/src/display.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#16846 fix: incorrect handling of `use` and panic issue in `extract_module`.
  crates/ide-assists/src/handlers/extract_module.rs
Labels: S-waiting-on-review

#16862 internal: remove redundant clone()s
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/tests.rs
  crates/hir/src/lib.rs
  crates/hir/src/term_search/tactics.rs
  crates/ide-completion/src/render.rs
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
  crates/ide-diagnostics/src/lib.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
Labels: S-waiting-on-review

#16861 fix: Ignore some warnings if they originate from within macro expansions
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/ide-diagnostics/src/handlers/remove_trailing_return.rs
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
  crates/ide-diagnostics/src/handlers/unused_variables.rs
  crates/ide-diagnostics/src/lib.rs
Labels: S-waiting-on-review

#16868 fix: handle attributes when typing curly bracket
  crates/ide/src/typing.rs
Labels: S-waiting-on-review

#16830 Fix panic with impl trait associated types in where clause
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/tests/traits.rs
Labels: S-waiting-on-review

#16839 Refactor extension to support arbitrary shell command runnables
  editors/code/src/run.ts
  editors/code/src/tasks.ts
Labels: S-waiting-on-review

#16822 fix: Make inlay hint resolving work better for inlays targetting the same position
  crates/ide/src/inlay_hints.rs
  crates/ide/src/inlay_hints/adjustment.rs
  crates/ide/src/inlay_hints/bind_pat.rs
  crates/ide/src/inlay_hints/binding_mode.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/ide/src/inlay_hints/closing_brace.rs
  crates/ide/src/inlay_hints/closure_captures.rs
  crates/ide/src/inlay_hints/closure_ret.rs
  crates/ide/src/inlay_hints/discriminant.rs
  crates/ide/src/inlay_hints/fn_lifetime_fn.rs
  crates/ide/src/inlay_hints/implicit_drop.rs
  crates/ide/src/inlay_hints/implicit_static.rs
  crates/ide/src/inlay_hints/param_name.rs
  crates/ide/src/inlay_hints/range_exclusive.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#16860 feat: Syntax highlighting improvements
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-completion/src/completions/keyword.rs
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/function.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-completion/src/tests/special.rs
  crates/ide-db/src/lib.rs
  crates/ide/src/file_structure.rs
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/ide/src/syntax_highlighting/html.rs
  crates/ide/src/syntax_highlighting/tags.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
  crates/ide/src/syntax_highlighting/test_data/highlight_attributes.html
  crates/ide/src/syntax_highlighting/test_data/highlight_block_mod_items.html
  crates/ide/src/syntax_highlighting/test_data/highlight_const.html
  crates/ide/src/syntax_highlighting/test_data/highlight_crate_root.html
  crates/ide/src/syntax_highlighting/test_data/highlight_default_library.html
  crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
  crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
  crates/ide/src/syntax_highlighting/test_data/highlight_general.html
  crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
  crates/ide/src/syntax_highlighting/test_data/highlight_keywords.html
  crates/ide/src/syntax_highlighting/test_data/highlight_lifetimes.html
  crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
  crates/ide/src/syntax_highlighting/test_data/highlight_module_docs_inline.html
  crates/ide/src/syntax_highlighting/test_data/highlight_module_docs_outline.html
  crates/ide/src/syntax_highlighting/test_data/highlight_operators.html
  crates/ide/src/syntax_highlighting/test_data/highlight_rainbow.html
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
  crates/ide/src/syntax_highlighting/tests.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/semantic_tokens.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
  crates/syntax/src/tests/sourcegen_ast.rs
Labels: S-waiting-on-review

#16852 feat: Implement ATPIT
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/chalk_ext.rs
  crates/hir-ty/src/db.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/coerce.rs
  crates/hir-ty/src/infer/path.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/layout.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/mir/monomorphization.rs
  crates/hir-ty/src/tests/traits.rs
Labels: S-waiting-on-author

#16871 fix: Skip problematic cyclic dev-dependencies
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#16880 Use `--workspace` and `--no-fail-fast` in test explorer
  crates/flycheck/src/test_runner.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/main_loop.rs
  editors/code/src/test_explorer.ts
Labels: S-waiting-on-review

#16883 minor: Do progress reporting for crate-graph construction
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
Labels: S-waiting-on-review

#16885 fix: Improve error recovery for match arms
  crates/parser/src/grammar/expressions/atom.rs
  crates/parser/test_data/parser/inline/err/0034_match_arms_recovery.rast
  crates/parser/test_data/parser/inline/err/0034_match_arms_recovery.rs
Labels: S-waiting-on-review

#16884 internal: Move grammar codegen into xtask
  .github/workflows/publish-libs.yaml
  Cargo.lock
  crates/hir-ty/Cargo.toml
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/ide-diagnostics/src/lib.rs
  crates/syntax/Cargo.toml
  crates/syntax/src/ast/generated/nodes.rs
  crates/syntax/src/ast/generated/tokens.rs
  crates/syntax/src/tests.rs
  xtask/Cargo.toml
  xtask/src/codegen.rs
  xtask/src/codegen/grammar.rs
  xtask/src/codegen/grammar/ast_src.rs
  xtask/src/flags.rs
Labels: S-waiting-on-review

#16886 internal: Delay drawing of workspace dev-dependency edges
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#16812 fix: Goto implementation to impls inside blocks
  crates/hir/src/lib.rs
  crates/ide/src/goto_implementation.rs
Labels: S-waiting-on-author

#16879 Add fuel to match checking
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Labels: S-waiting-on-review

#16889 internal: Enforce utf8 paths
  Cargo.lock
  Cargo.toml
  crates/flycheck/src/lib.rs
  crates/ide-diagnostics/Cargo.toml
  crates/ide-diagnostics/src/handlers/unlinked_file.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/doc_links/tests.rs
  crates/ide/src/lib.rs
  crates/load-cargo/Cargo.toml
  crates/load-cargo/src/lib.rs
  crates/paths/Cargo.toml
  crates/paths/src/lib.rs
  crates/proc-macro-api/Cargo.toml
  crates/proc-macro-api/src/msg.rs
  crates/proc-macro-api/src/process.rs
  crates/proc-macro-srv/src/dylib.rs
  crates/proc-macro-srv/src/lib.rs
  crates/project-model/Cargo.toml
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/lib.rs
  crates/project-model/src/project_json.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/bin/main.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/diagnostics.rs
  crates/rust-analyzer/src/cli/lsif.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/diagnostics/to_proto.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/crate_graph.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  crates/rust-analyzer/tests/slow-tests/testdir.rs
  crates/toolchain/Cargo.toml
  crates/toolchain/src/lib.rs
  crates/vfs-notify/src/lib.rs
  crates/vfs/src/vfs_path.rs
Labels: S-waiting-on-review

#16892 internal: Don't eagerly try to read crate root file contents before VFS
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/reload.rs
  crates/vfs/src/lib.rs
Labels: S-waiting-on-review

#16891 chore: remove repetitive words
  crates/hir-expand/src/cfg_process.rs
  crates/hir/src/term_search/tactics.rs
Labels: S-waiting-on-review

#16904 internal: Bump rust-cache action
  .github/workflows/ci.yaml
Labels: S-waiting-on-review

#16895 Resolve whether `$pat` is `$pat_param` or not via 🌟hygiene🌟
  Cargo.lock
  crates/base-db/src/input.rs
  crates/base-db/src/lib.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/mbe.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/path_resolution.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-expand/src/lib.rs
  crates/hir-ty/Cargo.toml
  crates/hir-ty/src/method_resolution.rs
  crates/hir/src/lib.rs
  crates/ide/Cargo.toml
  crates/ide/src/lib.rs
  crates/mbe/src/benchmark.rs
  crates/mbe/src/expander.rs
  crates/mbe/src/expander/matcher.rs
  crates/mbe/src/expander/transcriber.rs
  crates/mbe/src/lib.rs
  crates/mbe/src/parser.rs
  crates/project-model/Cargo.toml
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/project_json.rs
  crates/project-model/src/workspace.rs
  crates/span/src/lib.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#16909 fix: Keep the span for `Attr::Literal` around
  crates/hir-def/src/attr.rs
  crates/hir-def/src/lang_item.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/attrs.rs
  crates/hir/src/lib.rs
  crates/ide-completion/src/context.rs
  crates/ide-diagnostics/src/tests.rs
  crates/ide/src/status.rs
Labels: S-waiting-on-review

#16911 fix: Fix projects depending on `rustc_private` hanging
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#16835 Have Derive Attribute share a token tree with it's proc macros.
  crates/hir-def/src/nameres/attr_resolution.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/cfg_process.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/lib.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review, S-waiting-on-decision

#16912 internal: Remove span trait
  Cargo.lock
  crates/base-db/src/input.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/to_parser_input.rs
  crates/mbe/src/tt_iter.rs
  crates/proc-macro-api/src/msg/flat.rs
  crates/proc-macro-srv/src/lib.rs
  crates/proc-macro-srv/src/server/token_stream.rs
  crates/rust-analyzer/src/reload.rs
  crates/tt/Cargo.toml
  crates/tt/src/lib.rs
Labels: S-waiting-on-review

#16913 fix: Some file watching related vfs fixes
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/reload.rs
  crates/vfs-notify/src/lib.rs
  crates/vfs/src/lib.rs
  crates/vfs/src/loader.rs
Labels: S-waiting-on-review

#16918 fix: Don't assert paths being utf8 when filtering them in the watcher
  crates/paths/src/lib.rs
  crates/project-model/src/cargo_workspace.rs
  crates/vfs-notify/src/lib.rs
Labels: S-waiting-on-review

#16919 fix: handle self::super when lowering UseTree
  crates/hir-expand/src/mod_path.rs
Labels: S-waiting-on-review

#16905 internal: Rename ProcMacroKind::FuncLike to Bang
  crates/base-db/src/input.rs
  crates/hir-def/src/data.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/proc_macro.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/proc_macro.rs
  crates/hir/src/lib.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_attributes.html
  crates/ide/src/syntax_highlighting/tests.rs
  crates/load-cargo/src/lib.rs
  crates/proc-macro-api/src/lib.rs
  crates/proc-macro-srv/src/proc_macros.rs
  crates/proc-macro-srv/src/tests/mod.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#16927 fix: Rename `func_like` to `FuncLike`
  crates/proc-macro-api/src/lib.rs
Labels: S-waiting-on-review

#16928 internal: Build x86_64-unknown-linux-gnu releases on Rocky Linux 8
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16929 internal: Bump release actions and Node
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16915 fix: Prevent stack overflow in recursive const types
  crates/hir-ty/src/consteval/tests.rs
  crates/hir-ty/src/mir/eval.rs
Labels: S-waiting-on-review

#16935 Handle panicking like rustc CTFE does
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#16944 Revert to the crates.io version of rustc_pattern_analysis
  crates/hir-ty/src/lib.rs
Labels: S-waiting-on-review

#16930 internal: Support choosing the allocator in `xtask dist`
  crates/rust-analyzer/src/cli/flags.rs
  xtask/src/dist.rs
  xtask/src/flags.rs
  xtask/src/install.rs
Labels: S-waiting-on-review

#16906 feat: limit struct hover display nums
  crates/hir/src/display.rs
  crates/ide/src/hover.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-author

#16805 feat: Implement resolving and lowering of Lifetimes (no inference yet)
  crates/hir-def/src/generics.rs
  crates/hir-def/src/resolver.rs
  crates/hir-ty/src/builder.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/path.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/mapping.rs
  crates/hir-ty/src/mir/monomorphization.rs
  crates/hir-ty/src/tests/display_source_code.rs
  crates/hir-ty/src/tests/patterns.rs
  crates/hir-ty/src/tests/regression.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/extract_function.rs
  crates/ide-assists/src/handlers/generate_delegate_methods.rs
  crates/ide-completion/src/tests/predicate.rs
  crates/ide-completion/src/tests/type_pos.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-author

#16951 minor: Update comment on provenance_split
  crates/hir-ty/src/utils.rs
Labels: S-waiting-on-review

#16964 fix: Revert debug extension priorities
  editors/code/src/debug.ts
Labels: S-waiting-on-review

#16965 fix: use lldb when debugging with C++ extension on MacOS
  editors/code/src/debug.ts
Labels: S-waiting-on-review

#16957 fix: check for client support of relative glob patterns before using them
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/reload.rs
Labels: S-waiting-on-review

#16967 fix: ADT hover considering only type or const len not lifetimes
  crates/hir/src/lib.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#16971 Resolve tests per file instead of per crate in test explorer
  crates/ide/src/lib.rs
  crates/ide/src/test_explorer.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/dev/lsp-extensions.md
  editors/code/src/lsp_ext.ts
  editors/code/src/test_explorer.ts
Labels: S-waiting-on-review

#16974 refactor: Implement len and is_empty method in generic_params
  crates/hir-def/src/generics.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#16975 Prompt the user to reload the window when enabling test explorer
  editors/code/src/config.ts
Labels: S-waiting-on-review
