Repository rust-lang/rust-analyzer, pull requests merged in 2024-02, with the labels that each got.

#16468 minor: Recommend maintained Neovim plugin in documentation
  docs/user/manual.adoc
Labels: S-waiting-on-review

#16416 internal: VS Code: report conflict with `panicbit.cargo`
  editors/code/src/main.ts
Labels: S-waiting-on-review

#16451 internal: Work through temporarily allowed clippy lints, part 2
  Cargo.toml
  crates/flycheck/src/lib.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/body/tests.rs
  crates/hir-def/src/data.rs
  crates/hir-def/src/hir/format_args.rs
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/macro_expansion_tests/mod.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/path_resolution.rs
  crates/hir-def/src/per_ns.rs
  crates/hir-def/src/test_db.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-ty/src/inhabitedness.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/attrs.rs
  crates/hir/src/lib.rs
  crates/ide-assists/src/tests/sourcegen.rs
  crates/ide-completion/src/context/analysis.rs
  crates/ide-completion/src/tests.rs
  crates/ide-db/src/imports/merge_imports.rs
  crates/ide/src/hover.rs
  crates/proc-macro-api/src/lib.rs
  crates/proc-macro-api/src/msg.rs
  crates/proc-macro-srv-cli/src/main.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/diagnostics.rs
  crates/rust-analyzer/src/cli/lsif.rs
  crates/rust-analyzer/src/cli/run_tests.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/cli/ssr.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/stdx/src/macros.rs
  crates/syntax/src/ast/make.rs
  crates/syntax/src/tests.rs
Labels: S-waiting-on-author

#16476 internal: sync from downstream
  Cargo.lock
  Cargo.toml
  crates/parser/src/lexed_str.rs
  crates/syntax/src/ast/token_ext.rs
  crates/syntax/src/validation.rs
Labels: S-waiting-on-review

#16469 internal: add typos check CI (part 2)
  .github/workflows/ci.yaml
  .typos.toml
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
  crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/path_resolution.rs
  crates/hir-def/src/visibility.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/tests/traits.rs
  crates/ide-assists/src/handlers/generate_default_from_new.rs
  crates/ide-assists/src/handlers/generate_delegate_trait.rs
  crates/ide-assists/src/handlers/into_to_qualified_from.rs
  crates/ide-db/src/generated/lints.rs
  crates/ide/src/folding_ranges.rs
  crates/mbe/src/syntax_bridge.rs
  crates/proc-macro-api/src/version.rs
  docs/dev/lsp-extensions.md
  docs/dev/style.md
Labels: S-waiting-on-review

#16479 internal: Use MacOS 12 runners for releases
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16485 minor: polish warning msg
  editors/code/src/main.ts
Labels: S-waiting-on-review

#16492 internal: Sync from downstream
  crates/hir-ty/src/layout/target.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/utils.rs
Labels: S-waiting-on-review

#16480 Remove unused Subtree::visit_ids function
  crates/tt/src/lib.rs
Labels: S-waiting-on-review

#16474 internal: even more `tracing`
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/visibility.rs
  crates/hir-ty/src/autoderef.rs
  crates/hir-ty/src/builder.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir/src/lib.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-db/src/imports/import_assets.rs
Labels: S-waiting-on-review

#16482 Swap Subtree::token_trees from Vec to boxed slice
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-expand/src/builtin_attr_macro.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/fixup.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/quote.rs
  crates/mbe/src/benchmark.rs
  crates/mbe/src/expander.rs
  crates/mbe/src/expander/matcher.rs
  crates/mbe/src/expander/transcriber.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/tt_iter.rs
  crates/proc-macro-api/src/msg.rs
  crates/proc-macro-api/src/msg/flat.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
  crates/proc-macro-srv/src/server/token_stream.rs
  crates/test-fixture/src/lib.rs
  crates/tt/src/buffer.rs
  crates/tt/src/lib.rs
Labels: S-waiting-on-review

#16493 fix: emit parser error for missing argument list
  crates/parser/src/grammar/expressions.rs
  crates/parser/test_data/parser/inline/err/0028_method_call_missing_argument_list.rast
  crates/parser/test_data/parser/inline/err/0028_method_call_missing_argument_list.rs
Labels: S-waiting-on-review

#16496 minor: remove clones
  crates/ide-db/src/imports/insert_use.rs
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#16499 internal: Update rustc_pattern_analysis dependency
  Cargo.lock
  Cargo.toml
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
Labels: S-waiting-on-review

#16500 internal: run Clippy on Windows
  .github/workflows/ci.yaml
Labels: S-waiting-on-review

#16501 minor: Add `lete` to postfix completion list
  crates/ide-completion/src/lib.rs
Labels: S-waiting-on-review

#16505 Optimize input queries that take no arguments
  crates/salsa/salsa-macros/src/query_group.rs
  crates/salsa/src/input.rs
  crates/salsa/src/plumbing.rs
Labels: S-waiting-on-review

#16506 minor: bump `paths-filter`
  .github/workflows/ci.yaml
Labels: S-waiting-on-review

#16507 minor: Remove `ffi_returns_twice` references
  crates/hir-def/src/attr/builtin.rs
  crates/ide-db/src/generated/lints.rs
Labels: S-waiting-on-review

#16509 fix: Fix tuple structs not rendering visibility in their fields
  crates/hir/src/display.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#16124 fix: Recover from missing argument in call expressions
  crates/parser/src/grammar.rs
  crates/parser/src/grammar/expressions.rs
  crates/parser/src/grammar/generic_args.rs
  crates/parser/src/grammar/generic_params.rs
  crates/parser/src/grammar/items/adt.rs
  crates/parser/src/grammar/items/use_item.rs
  crates/parser/test_data/parser/inline/err/0015_arg_list_recovery.rast
  crates/parser/test_data/parser/inline/err/0015_arg_list_recovery.rs
  crates/parser/test_data/parser/inline/err/0026_use_tree_list_err_recovery.rast
  crates/parser/test_data/parser/inline/err/0026_use_tree_list_err_recovery.rs
  crates/parser/test_data/parser/inline/err/0029_tuple_field_list_recovery.rast
  crates/parser/test_data/parser/inline/err/0029_tuple_field_list_recovery.rs
  crates/parser/test_data/parser/inline/err/0030_generic_arg_list_recover.rast
  crates/parser/test_data/parser/inline/err/0030_generic_arg_list_recover.rs
  crates/parser/test_data/parser/inline/err/0031_generic_param_list_recover.rast
  crates/parser/test_data/parser/inline/err/0031_generic_param_list_recover.rs
Labels: S-waiting-on-author

#16462 Better error message for when proc-macros have not yet been built
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/unresolved_proc_macro.rs
  crates/rust-analyzer/src/reload.rs
Labels: S-waiting-on-review

#16454 feat: Add break and return postfix keyword completions
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/completions/expr.rs
  crates/ide-completion/src/completions/item_list.rs
  crates/ide-completion/src/completions/keyword.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/completions/record.rs
  crates/ide-completion/src/completions/snippet.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/context/analysis.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-completion/src/tests/proc_macros.rs
  crates/ide-completion/src/tests/special.rs
  crates/ide-db/src/famous_defs.rs
  crates/ide/src/hover/tests.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#16502 feat: Add "unnecessary else" diagnostic and fix
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir/src/diagnostics.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide-diagnostics/src/tests.rs
Labels: S-waiting-on-review

#16477 feat: Add incorrect case diagnostics for traits and their associated items
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/incorrect_case.rs
  crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
  crates/ide-diagnostics/src/tests.rs
Labels: S-waiting-on-review

#16487 Remove unnecessary `.as_ref()` in generate getter assist
  crates/ide-assists/src/handlers/generate_getter_or_setter.rs
  crates/ide-assists/src/tests/generated.rs
  crates/ide-assists/src/utils.rs
Labels: S-waiting-on-review

#16460 feat: Add diagnostic with fix to replace trailing `return <val>;` with `<val>`
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir/src/diagnostics.rs
  crates/ide-diagnostics/src/handlers/remove_trailing_return.rs
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide-diagnostics/src/tests.rs
Labels: S-waiting-on-review

#16467 internal: Migrate assists to the structured snippet API, part 6/7
  crates/ide-assists/src/handlers/extract_function.rs
  crates/ide-assists/src/handlers/generate_delegate_methods.rs
  crates/ide-assists/src/handlers/generate_delegate_trait.rs
  crates/ide-assists/src/handlers/generate_function.rs
  crates/ide-assists/src/handlers/generate_getter_or_setter.rs
  crates/ide-assists/src/handlers/generate_impl.rs
  crates/ide-assists/src/handlers/generate_new.rs
  crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
  crates/ide-assists/src/tests.rs
  crates/ide-assists/src/tests/generated.rs
  crates/ide-assists/src/utils.rs
  crates/syntax/src/ast/edit_in_place.rs
  crates/syntax/src/ast/make.rs
Labels: S-waiting-on-review

#16517 internal: fix crash inside `filter_unnecessary_bounds` for a missing generic param
  crates/ide-assists/src/handlers/generate_function.rs
Labels: S-waiting-on-review

#16424 implement convert to guarded return assist for `let` statement with type that implements `std::ops::Try`
  crates/ide-assists/src/handlers/convert_to_guarded_return.rs
Labels: S-waiting-on-author

#16518 Enable some minor lints that we should tackles
  Cargo.toml
  crates/hir-def/src/attr.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/lib.rs
  crates/hir-expand/src/ast_id_map.rs
  crates/hir-expand/src/db.rs
  crates/hir/src/attrs.rs
  crates/syntax/src/ptr.rs
  lib/la-arena/src/lib.rs
Labels: S-waiting-on-review

#16519 internal: Enable some minor lints that we should tackles (take2)
  Cargo.toml
  crates/hir-def/src/generics.rs
  crates/hir-def/src/lib.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/mir/lower.rs
  crates/ide/src/inlay_hints/implicit_drop.rs
  crates/ide/src/inlay_hints/range_exclusive.rs
Labels: S-waiting-on-review

#16497 Fix incorrect inlining of functions that come from MBE macros
  crates/ide-assists/src/handlers/inline_call.rs
Labels: S-waiting-on-author

#16525 Abstract more over ItemTreeLoc-like structs
  crates/hir-def/src/attr.rs
  crates/hir-def/src/child_by_source.rs
  crates/hir-def/src/generics.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/src.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/lower.rs
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/convert_bool_then.rs
  crates/ide-assists/src/handlers/generate_documentation_template.rs
  crates/ide-assists/src/handlers/into_to_qualified_from.rs
  crates/ide-assists/src/handlers/qualify_path.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/const_.rs
  crates/ide-completion/src/render/function.rs
  crates/ide-completion/src/render/type_alias.rs
  crates/ide-db/src/defs.rs
  crates/ide-db/src/imports/import_assets.rs
  crates/ide-db/src/traits.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/goto_declaration.rs
  crates/ide/src/goto_definition.rs
  crates/ide/src/goto_implementation.rs
  crates/ide/src/runnables.rs
  crates/ide/src/syntax_highlighting/highlight.rs
Labels: S-waiting-on-review

#16524 minor: test that flip_trait_bound works with trait objects
  crates/ide-assists/src/handlers/flip_trait_bound.rs
Labels: S-waiting-on-review

#16526 internal: Cleanup 🧹
  crates/hir-def/src/attr.rs
  crates/hir-def/src/child_by_source.rs
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/generics.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/resolver.rs
  crates/hir-def/src/src.rs
  crates/hir-def/src/trace.rs
  crates/hir-def/src/visibility.rs
  crates/ide-diagnostics/src/handlers/private_field.rs
Labels: S-waiting-on-review

#16527 internal: Remove SELF_REF hack for self referential SyntaxContexts
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/mbe.rs
  crates/hir-expand/src/hygiene.rs
  crates/hir-expand/src/lib.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/db.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/layout.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/monomorphization.rs
  crates/hir/src/lib.rs
  crates/salsa/src/interned.rs
  crates/salsa/src/lib.rs
  crates/span/src/lib.rs
Labels: S-waiting-on-review

#16533 Update to latest `rustc_pattern_analysis`
  Cargo.lock
  Cargo.toml
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Labels: S-waiting-on-review

#16530 fix: Fix macro transcriber emitting incorrect lifetime tokens
  crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
  crates/mbe/src/expander/transcriber.rs
  crates/mbe/src/syntax_bridge.rs
  crates/tt/src/lib.rs
Labels: S-waiting-on-review

#15923 feat: ignored and disabled macro expansion
  crates/base-db/src/input.rs
  crates/hir-def/src/data.rs
  crates/hir-def/src/macro_expansion_tests/mod.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/diagnostics.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/proc_macro.rs
  crates/load-cargo/src/lib.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/reload.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-author

#16092 feat: Introduce term search to rust-analyzer
  crates/hir-def/src/attr.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir/src/lib.rs
  crates/hir/src/term_search.rs
  crates/hir/src/term_search/expr.rs
  crates/hir/src/term_search/tactics.rs
  crates/ide-assists/src/handlers/term_search.rs
  crates/ide-assists/src/lib.rs
  crates/ide-completion/src/completions.rs
  crates/ide-completion/src/completions/expr.rs
  crates/ide-completion/src/config.rs
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/tests.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-completion/src/tests/record.rs
  crates/ide-completion/src/tests/special.rs
  crates/ide-db/src/famous_defs.rs
  crates/ide-db/src/path_transform.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/ide-diagnostics/src/handlers/typed_hole.rs
  crates/ide-diagnostics/src/tests.rs
  crates/ide/src/hover/tests.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/flags.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/syntax/src/ast/node_ext.rs
  crates/test-utils/src/minicore.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-blocked

#15476 Substitute $saved_file in custom check commands
  crates/flycheck/src/lib.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-author

#16541 Highlight rustdoc
  editors/code/.vscodeignore
  editors/code/language-configuration-rustdoc.json
  editors/code/package.json
  editors/code/rustdoc-inject.json
  editors/code/rustdoc.json
Labels: S-waiting-on-review

#16540 internal: macro_arg query always returns a TokenTree
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/expander.rs
  crates/hir-def/src/macro_expansion_tests/mbe/matching.rs
  crates/hir-def/src/macro_expansion_tests/mbe/meta_syntax.rs
  crates/hir-def/src/macro_expansion_tests/mbe/metavar_expr.rs
  crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-expand/src/lib.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-diagnostics/src/handlers/macro_error.rs
Labels: S-waiting-on-review

#16545 fix: Fix target layout fetching
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/target_data_layout.rs
Labels: S-waiting-on-review

#16546 minor: remove eprintln! macro
  crates/ide-assists/src/lib.rs
  crates/ide/src/lib.rs
  crates/syntax/src/lib.rs
Labels: S-waiting-on-review

#16446 Implement `literal_from_str` for proc macro server
  Cargo.lock
  crates/proc-macro-srv/Cargo.toml
  crates/proc-macro-srv/src/server.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
  crates/syntax/src/ast/token_ext.rs
  crates/syntax/src/lib.rs
Labels: S-waiting-on-author

#16547 fix: Validate literals in proc-macro-srv FreeFunctions::literal_from_str
  Cargo.lock
  crates/proc-macro-srv/Cargo.toml
  crates/proc-macro-srv/src/lib.rs
  crates/proc-macro-srv/src/server.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
  crates/proc-macro-srv/src/tests/mod.rs
  crates/syntax/src/ast/token_ext.rs
  crates/syntax/src/lib.rs
Labels: S-waiting-on-review

#16117 feat: completion list suggests constructor like & builder methods first
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/function.rs
Labels: S-waiting-on-author

#16550 Activate on top level `Cargo.toml` and `rust-project.json` files
  editors/code/package.json
Labels: S-waiting-on-review

#16544 Add completions to show only traits in trait `impl` statement
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/completions/type.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/tests/flyimport.rs
  crates/ide-completion/src/tests/type_pos.rs
Labels: S-waiting-on-review

#16558 Update JsonProject to include optional fields
  editors/code/src/rust_project.ts
Labels: S-waiting-on-review

#16560 internal: Set channel override when querying the sysroot metadata
  crates/project-model/src/sysroot.rs
  xtask/src/metrics.rs
Labels: S-waiting-on-review

#16562 internal: Add a clippy and rustfmt problem matcher to CI
  .github/rust.json
  .github/workflows/ci.yaml
  crates/rust-analyzer/tests/slow-tests/tidy.rs
Labels: S-waiting-on-review

#16563 fix: Set `RUSTUP_TOOLCHAIN` and invoke the proxies instead of directly invoking sysroot binaries
  crates/flycheck/src/lib.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/target_data_layout.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/reload.rs
Labels: S-waiting-on-review

#16247 fix: Fix build scripts not being rebuilt in some occasions
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/lib.rs
  crates/hir-expand/src/proc_macro.rs
  crates/ide/src/parent_module.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cargo_target_spec.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-author

#15003 feature: Add basic support for `become` expr/tail calls
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/hir.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/mutability.rs
  crates/hir-ty/src/mir/lower.rs
  crates/ide-db/src/syntax_helpers/node_ext.rs
  crates/parser/src/grammar/expressions/atom.rs
  crates/parser/src/syntax_kind/generated.rs
  crates/parser/test_data/parser/inline/ok/0209_become_expr.rast
  crates/parser/test_data/parser/inline/ok/0209_become_expr.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
  crates/syntax/src/ast/prec.rs
  crates/syntax/src/tests/ast_src.rs
Labels: S-waiting-on-author, S-blocked

#16559 Set documentation field in SCIP from doc comment
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/cli/scip.rs
Labels: S-waiting-on-review

#16569 fix: Place snippets correctly in multi-edit assists
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#16573 internal: Remove salsa doc compile tests
  crates/rust-analyzer/src/bin/main.rs
  crates/rust-analyzer/src/bin/rustc_wrapper.rs
  crates/salsa/src/doctest.rs
  crates/salsa/src/lib.rs
Labels: S-waiting-on-review

#16574 fix: Fix "needless return" diagnostic for trailing item declarations
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/body/scope.rs
  crates/hir-def/src/hir.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/mutability.rs
  crates/hir-ty/src/mir/lower.rs
  crates/ide-diagnostics/src/handlers/remove_trailing_return.rs
Labels: S-waiting-on-review

#16577 internal: Migrate assists to the structured snippet API, part 7/7
  crates/ide-assists/src/handlers/fix_visibility.rs
  crates/ide-assists/src/handlers/generate_trait_from_impl.rs
  crates/ide-assists/src/tests/generated.rs
  crates/ide-db/src/source_change.rs
  crates/syntax/src/ast/edit_in_place.rs
  crates/syntax/src/ast/make.rs
Labels: S-waiting-on-review

#16576 lsp-server: add license files
  lib/lsp-server/LICENSE-APACHE
  lib/lsp-server/LICENSE-MIT
Labels: S-waiting-on-review

#16582 fix: Respect textual length of paths in find-path
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/hir.rs
  crates/hir-expand/src/mod_path.rs
Labels: S-waiting-on-review

#16583 fix: Don't show type mismatches for `{unknown}` to non-`{unknown}` mismatches
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/tests/diagnostics.rs
  crates/hir-ty/src/tests/simple.rs
Labels: S-waiting-on-review

#16585 internal: bump `actions/checkout` to v4
  .github/workflows/autopublish.yaml
  .github/workflows/ci.yaml
  .github/workflows/fuzz.yml
  .github/workflows/metrics.yaml
  .github/workflows/publish-libs.yaml
  .github/workflows/release.yaml
  .github/workflows/rustdoc.yaml
Labels: S-waiting-on-review

#16587 ci: Update GitHub Actions and Node version
  .github/workflows/ci.yaml
  .github/workflows/metrics.yaml
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16586 fix: Remove cargo knowledge from `CrateData`
  crates/base-db/src/input.rs
  crates/base-db/src/lib.rs
  crates/hir-expand/src/change.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-ty/src/layout/target.rs
  crates/hir-ty/src/layout/tests.rs
  crates/ide-completion/src/context.rs
  crates/ide-db/src/rename.rs
  crates/ide-diagnostics/src/handlers/incorrect_case.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/lib.rs
  crates/ide/src/rename.rs
  crates/ide/src/shuffle_crate_graph.rs
  crates/ide/src/status.rs
  crates/load-cargo/src/lib.rs
  crates/project-model/src/project_json.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/project-model/test_data/output/cargo_hello_world_project_model.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt
  crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lib.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/crate_graph.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  crates/rust-analyzer/tests/test_data/deduplication_crate_graph_A.json
  crates/rust-analyzer/tests/test_data/deduplication_crate_graph_B.json
  crates/test-fixture/src/lib.rs
  crates/test-utils/src/fixture.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#16588 internal: Parse (nightly) `const` and `async` trait bounds
  crates/parser/src/grammar/generic_params.rs
  crates/parser/test_data/parser/inline/ok/0211_async_trait_bound.rast
  crates/parser/test_data/parser/inline/ok/0211_async_trait_bound.rs
  crates/parser/test_data/parser/inline/ok/0212_const_trait_bound.rast
  crates/parser/test_data/parser/inline/ok/0212_const_trait_bound.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
Labels: S-waiting-on-review

#16579 fix: Fix snippets being placed leftwards of where they should be
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#16597 internal: Sync from downstream
  crates/hir-def/src/attr/builtin.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
Labels: S-waiting-on-review

#16598 internal: Downgrade actions/checkout in release workflow
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16599 internal: Also downgrade actions/setup-node
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16600 internal: Also downgrade node to 16
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#16601 fix: checkout repo before run typos
  .github/workflows/ci.yaml
  crates/hir/src/term_search/tactics.rs
  crates/ide-completion/src/item.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  crates/salsa/src/lib.rs
  crates/salsa/src/lru.rs
Labels: S-waiting-on-review

#16475 feat: Support multiple tab stops for completions in VSCode
  editors/code/src/commands.ts
  editors/code/src/snippets.ts
Labels: S-waiting-on-review

#16358 Deduplicate references when some of them are in macro expansions
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/stdx/src/lib.rs
Labels: S-waiting-on-author

#16489 feat!: create alias when renaming an import.
  crates/ide/src/rename.rs
Labels: S-waiting-on-review

#16590 fix: Fix false positives for "unnecessary else" diagnostic
  crates/hir-ty/src/diagnostics/expr.rs
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
Labels: S-waiting-on-author

#16589 feat: add unresolved-ident diagnostic
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir/src/diagnostics.rs
  crates/ide-diagnostics/src/handlers/inactive_code.rs
  crates/ide-diagnostics/src/handlers/incorrect_case.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
  crates/ide-diagnostics/src/handlers/mutability_errors.rs
  crates/ide-diagnostics/src/handlers/remove_trailing_return.rs
  crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/ide-diagnostics/src/handlers/undeclared_label.rs
  crates/ide-diagnostics/src/handlers/unresolved_field.rs
  crates/ide-diagnostics/src/handlers/unresolved_ident.rs
  crates/ide-diagnostics/src/handlers/unresolved_method.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide-diagnostics/src/tests.rs
Labels: S-waiting-on-author

#13112 Setup infra for handling auto trait bounds disabled due to perf problems
  crates/hir-def/src/data/adt.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/db.rs
  crates/hir-ty/src/tests/traits.rs
  crates/hir/src/lib.rs
  crates/ide-db/src/apply_change.rs
  crates/ide-db/src/lib.rs
Labels: S-blocked

#16612 internal: Fetch toolchain and datalayout for DetachedFiles
  crates/hir-def/src/body/pretty.rs
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/tests/macros.rs
  crates/hir-ty/src/diagnostics/match_check/pat_util.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/hir-ty/src/mir/eval/shim/simd.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/ide-assists/src/handlers/generate_delegate_methods.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-db/src/imports/insert_use/tests.rs
  crates/ide-db/src/symbol_index.rs
  crates/ide/src/join_lines.rs
  crates/load-cargo/src/lib.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cargo_target_spec.rs
  crates/rust-analyzer/src/cli/lsif.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/salsa/salsa-macros/src/query_group.rs
  crates/salsa/src/debug.rs
  crates/salsa/src/derived.rs
  crates/salsa/src/input.rs
  crates/salsa/src/interned.rs
Labels: S-waiting-on-review

#16606 internal: Render assoc item owner in hover for items other than functions
  crates/hir/src/lib.rs
  crates/ide-db/src/defs.rs
  crates/ide/src/hover.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/static_index.rs
Labels: S-waiting-on-review

#16616 fix: server hanging up on build script task
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/lsp/utils.rs
  crates/rust-analyzer/src/reload.rs
Labels: S-waiting-on-review

#16617 internal: Attempt to add a timeout to rustc-tests
  crates/ide-diagnostics/src/handlers/useless_braces.rs
  crates/ide-diagnostics/src/lib.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
Labels: S-waiting-on-review

#16637 fix: Fix proc-macro server not accounting for string delimiters correctly
  crates/proc-macro-api/src/process.rs
  crates/proc-macro-srv/src/proc_macros.rs
  crates/proc-macro-srv/src/server.rs
  crates/proc-macro-srv/src/server/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server/token_id.rs
  crates/proc-macro-srv/src/server/token_stream.rs
  crates/proc-macro-srv/src/tests/mod.rs
Labels: S-waiting-on-review

#16645 fix: Fix deadlock in `recreate_crate_graph` <-> `file_line_index`
  crates/rust-analyzer/src/reload.rs
Labels: S-waiting-on-review

#16646 remove repetitive words
  crates/hir-ty/src/db.rs
  crates/salsa/src/runtime/dependency_graph.rs
Labels: S-waiting-on-review

#16643 internal: Optimize salsa memory usage
  Cargo.lock
  crates/ide-db/src/apply_change.rs
  crates/salsa/Cargo.toml
  crates/salsa/salsa-macros/src/database_storage.rs
  crates/salsa/salsa-macros/src/query_group.rs
  crates/salsa/src/derived.rs
  crates/salsa/src/derived/slot.rs
  crates/salsa/src/durability.rs
  crates/salsa/src/input.rs
  crates/salsa/src/interned.rs
  crates/salsa/src/lib.rs
  crates/salsa/src/plumbing.rs
  crates/salsa/src/revision.rs
  crates/salsa/src/runtime.rs
  crates/salsa/src/runtime/local_state.rs
  crates/salsa/tests/incremental/memoized_volatile.rs
  crates/salsa/tests/on_demand_inputs.rs
  crates/salsa/tests/storage_varieties/tests.rs
Labels: S-waiting-on-review

#16649 internal: Disable rustc test metrics
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#16621 fix: Recompiles due to RUSTC_BOOTSTRAP
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/target_data_layout.rs
Labels: S-waiting-on-review

#16650 Fix: Fix metrics CI failing
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#16652 internal: fix deadlock introduced by #16643
  crates/salsa/src/derived.rs
Labels: S-waiting-on-review

#16654 Add short flag -V for consistency with other rust tooling
  crates/rust-analyzer/src/cli/flags.rs
Labels: S-waiting-on-review

#16627 update bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: S-waiting-on-review

#16670 Document nvim 0.10 `inlay_hint`
  docs/user/manual.adoc
Labels: S-waiting-on-review

#16665 Prioritise rustup sysroots over system ones
  crates/toolchain/src/lib.rs
Labels: S-waiting-on-review

#16669 Merge `BorrowKind::Unique` into `BorrowKind::Mut`
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/mir.rs
  crates/hir-ty/src/mir/borrowck.rs
  crates/hir-ty/src/mir/lower/as_place.rs
  crates/hir-ty/src/mir/lower/pattern_matching.rs
  crates/hir-ty/src/mir/pretty.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#16647 fix: replace_filter_map_next_with_find_map shouldn't work for dyn trait
  crates/hir-ty/src/diagnostics/expr.rs
  crates/ide-diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
Labels: S-waiting-on-author

#16673 Narrow down typos ignores
  .typos.toml
Labels: S-waiting-on-author

#16679 fix: Fix modules in blocks not resolving in ide layer
  crates/base-db/src/input.rs
  crates/hir-def/src/body/tests/block.rs
  crates/hir-def/src/child_by_source.rs
  crates/hir-def/src/dyn_map/keys.rs
  crates/hir-def/src/nameres.rs
  crates/hir-def/src/resolver.rs
  crates/hir/src/semantics/source_to_def.rs
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_block_mod_items.html
  crates/ide/src/syntax_highlighting/test_data/highlight_rainbow.html
  crates/ide/src/syntax_highlighting/tests.rs
Labels: S-waiting-on-review

#16678 fix: panic when inlining callsites inside macros' parameters
  crates/ide-assists/src/handlers/inline_call.rs
Labels: S-waiting-on-review

#16684 fix: Don't panic on synthetic syntax in inference diagnostics
  crates/hir/src/diagnostics.rs
  crates/ide-diagnostics/src/handlers/unresolved_ident.rs
Labels: S-waiting-on-review

#16555 performance: Speed up Method Completions By Taking Advantage of Orphan Rules
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/traits.rs
  crates/hir/src/lib.rs
  crates/ide-completion/src/tests/flyimport.rs
  crates/ide-db/src/imports/import_assets.rs
Labels: S-waiting-on-author

#16691 fix: Fix completions panicking with certain macro setups
  Cargo.toml
  crates/hir-ty/src/method_resolution.rs
  crates/hir/src/semantics.rs
  crates/ide-completion/src/context/analysis.rs
  xtask/src/flags.rs
  xtask/src/install.rs
Labels: S-waiting-on-review

#16692 internal: Remove dead branches in `method_resolution::is_valid_candidate`
  crates/hir-ty/src/method_resolution.rs
Labels: S-waiting-on-review

#16651 Add assist for filling fields by replacing ellipsis in record syntax
  crates/ide-assists/src/handlers/fill_record_pattern_fields.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-author

#16687 feat: Add "make tuple" tactic to term search
  crates/hir/src/lib.rs
  crates/hir/src/term_search.rs
  crates/hir/src/term_search/expr.rs
  crates/hir/src/term_search/tactics.rs
  crates/ide-assists/src/handlers/term_search.rs
  crates/ide-completion/src/render.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-review

#16693 fix: rust-project.json projects not preferring sysroot rustc
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/target_data_layout.rs
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#16630 fix: Wrong closure kind deduction for closures with predicates
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/tests/patterns.rs
  crates/hir-ty/src/tests/regression.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir-ty/src/tests/traits.rs
  crates/hir-ty/src/traits.rs
  crates/hir-ty/src/utils.rs
Labels: S-waiting-on-author

#16696 fix: Goto definition for `deref_mut`
  crates/hir/src/source_analyzer.rs
  crates/ide/src/goto_definition.rs
Labels: S-waiting-on-review

#16697 Add `to_path_buf()` method for `RelPath`
  crates/paths/src/lib.rs
Labels: S-waiting-on-review

#16709 fix: Goto definition for `index_mut`
  crates/hir/src/source_analyzer.rs
  crates/ide/src/goto_definition.rs
Labels: S-waiting-on-review

#16638 feature: Add `destructure_struct_binding`
  crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
  crates/ide-assists/src/handlers/destructure_struct_binding.rs
  crates/ide-assists/src/handlers/destructure_tuple_binding.rs
  crates/ide-assists/src/handlers/fill_record_pattern_fields.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
  crates/ide-assists/src/utils.rs
  crates/ide-assists/src/utils/gen_trait_fn_body.rs
  crates/ide-assists/src/utils/ref_field_expr.rs
  crates/syntax/src/ast/make.rs
Labels: S-waiting-on-review

#16695 internal: Revert #16541
  editors/code/.vscodeignore
  editors/code/language-configuration-rustdoc.json
  editors/code/package.json
  editors/code/rustdoc-inject.json
  editors/code/rustdoc.json
Labels: S-waiting-on-review

#16698 Derive `PartialEq`, `Eq` & `Hash` for `hir::Param`
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#16705 Add public function for resolving callable AST exprs to their HIR equivalents
  crates/hir/src/semantics.rs
  crates/hir/src/source_analyzer.rs
Labels: S-waiting-on-review

#16706 internal: Remove load-cargo dependency on ide
  Cargo.lock
  crates/ide-db/Cargo.toml
  crates/ide-db/src/lib.rs
  crates/ide-db/src/prime_caches.rs
  crates/ide-db/src/prime_caches/topologic_sort.rs
  crates/ide/Cargo.toml
  crates/ide/src/lib.rs
  crates/ide/src/moniker.rs
  crates/load-cargo/Cargo.toml
  crates/load-cargo/src/lib.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/diagnostics.rs
  crates/rust-analyzer/src/cli/lsif.rs
  crates/rust-analyzer/src/cli/run_tests.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/cli/scip.rs
  crates/rust-analyzer/src/cli/ssr.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
Labels: S-waiting-on-review

#16707 Export `SemanticsImpl` from `ra_ap_hir` crate, since it's already exposed via `Semantics.deref()`
  crates/hir/src/lib.rs
Labels: S-waiting-on-review
