Repository rust-lang/rust-analyzer, pull requests merged in 2024-04, with the labels that each got.

#16986 update: add editor/extension information to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: S-waiting-on-review

#16970 Fix tasks in tasks.json
  editors/code/src/run.ts
  editors/code/src/tasks.ts
Labels: S-waiting-on-review

#16924 feat: Add `rust-analyzer.cargo.allTargets` to configure passing `--all-targets` to cargo invocations
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#16961 Fix crate IDs when multiple workspaces are loaded
  crates/project-model/src/project_json.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/handlers/notification.rs
Labels: S-waiting-on-review

#16979 pattern analysis: Use contiguous indices for enum variants
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
Labels: S-waiting-on-review

#16988 fix: Fix `allFeatures` config docs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#16920 internal: Fix new nightly clippy lints
  Cargo.toml
  crates/hir-ty/src/infer/pat.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/syntax_highlighting/tags.rs
  crates/intern/src/lib.rs
  crates/project-model/src/build_scripts.rs
  crates/rust-analyzer/src/cli/progress_report.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/slow-tests/tidy.rs
  crates/salsa/salsa-macros/src/database_storage.rs
  crates/salsa/salsa-macros/src/parenthesized.rs
  crates/salsa/salsa-macros/src/query_group.rs
  crates/salsa/src/derived.rs
  crates/salsa/src/derived/slot.rs
  crates/salsa/src/durability.rs
  crates/salsa/src/hash.rs
  crates/salsa/src/input.rs
  crates/salsa/src/intern_id.rs
  crates/salsa/src/interned.rs
  crates/salsa/src/lib.rs
  crates/salsa/src/lru.rs
  crates/salsa/src/plumbing.rs
  crates/salsa/src/revision.rs
  crates/salsa/src/runtime.rs
  crates/salsa/src/runtime/dependency_graph.rs
  crates/salsa/src/runtime/local_state.rs
  crates/salsa/src/storage.rs
  crates/sourcegen/src/lib.rs
  crates/test-utils/src/fixture.rs
  xtask/src/codegen.rs
  xtask/src/codegen/lints.rs
Labels: S-waiting-on-review

#16997 fix: Fix `patch_cfg_if` not applying with stitched sysroot
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#16996 internal: Lower outlive goals, respect them in display impls
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/generics.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/lib.rs
  crates/hir-ty/src/chalk_ext.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/coerce.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir-ty/src/infer/unify.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/lower/as_place.rs
  crates/hir-ty/src/tests/traits.rs
  crates/hir/src/display.rs
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/auto_import.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#17002 internal: Consider ADT generic parameter defaults for unsubstituted layout calculations
  crates/hir-ty/src/builder.rs
  crates/hir/src/lib.rs
  crates/ide/src/hover/tests.rs
  crates/proc-macro-api/src/lib.rs
Labels: S-waiting-on-review

#17006 fix: Fix some cfg censoring bugs
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-expand/src/cfg_process.rs
  crates/hir-expand/src/db.rs
  crates/ide-completion/src/completions/postfix.rs
Labels: S-waiting-on-review

#17003 Fix off-by-one error converting to LSP UTF8 offsets with multi-byte char
  crates/rust-analyzer/src/diagnostics/to_proto.rs
Labels: S-waiting-on-review

#17014 fix: Consider `exported_name="main"` functions in test modules as tests
  crates/hir-def/src/attr.rs
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/toggle_ignore.rs
  crates/ide-assists/src/utils.rs
  crates/ide/src/annotations/fn_references.rs
  crates/ide/src/runnables.rs
Labels: S-waiting-on-review

#17007 internal: Use jemalloc in releases
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#17016 Apply cargo flags in test explorer
  crates/flycheck/src/lib.rs
  crates/flycheck/src/test_runner.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-review

#17023 internal: Some cleanup and perf
  crates/base-db/src/input.rs
  crates/hir-def/src/data.rs
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/expander.rs
  crates/hir-def/src/generics.rs
  crates/hir-ty/src/consteval.rs
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/cast.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/monomorphization.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/lib.rs
  crates/ide/src/lib.rs
  crates/limit/Cargo.toml
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#17029 Revert "Use jemalloc for releases"
  .github/workflows/release.yaml
Labels: S-waiting-on-review

#17034 Document enabling the flatpak rust SDK extension
  docs/user/manual.adoc
Labels: S-waiting-on-review

#17033 Log flycheck errors
  crates/flycheck/src/lib.rs
Labels: S-waiting-on-review

#17056 Run cargo test per workspace in the test explorer
  crates/flycheck/src/command.rs
  crates/flycheck/src/lib.rs
  crates/flycheck/src/test_runner.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#17059 internal: make function builder create ast directly
  crates/ide-assists/src/handlers/generate_function.rs
Labels: S-waiting-on-review

#17030 internal: Bump chalk
  Cargo.lock
  Cargo.toml
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/tests/display_source_code.rs
  crates/hir-ty/src/tests/patterns.rs
  crates/hir-ty/src/tests/regression.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir-ty/src/tests/traits.rs
  crates/ide-assists/src/handlers/extract_function.rs
  crates/ide-assists/src/handlers/inline_call.rs
  crates/ide-assists/src/tests/generated.rs
  crates/ide-completion/src/tests/predicate.rs
  crates/ide-completion/src/tests/type_pos.rs
Labels: S-waiting-on-review

#17035 Run Windows tests on PRs too
  .github/workflows/ci.yaml
Labels: S-waiting-on-review

#17051 fix: support auto-closing for triple backticks
  editors/code/language-configuration.json
Labels: S-waiting-on-review

#17054 Revert "fix: set the right postfix snippets competion source range"
  crates/ide-completion/src/completions/postfix.rs
Labels: S-waiting-on-review

#17019 fix: VFS should not confuse paths with source roots that have the same prefix
  crates/vfs/src/file_set.rs
  crates/vfs/src/file_set/tests.rs
Labels: S-waiting-on-review

#17062 Temporarily disable unlinked file popup
  editors/code/src/client.ts
Labels: S-waiting-on-review

#17063 fix: Fix inlay hint resolution being broken
  crates/ide/src/inlay_hints.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#17064 minor: Carry inlay hint resolve hash as a string
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#16450 internal: Prepare parser interface for editions
  Cargo.lock
  crates/hir-def/src/macro_expansion_tests/mod.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/Cargo.toml
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/fixup.rs
  crates/hir-expand/src/name.rs
  crates/hir-ty/src/method_resolution.rs
  crates/mbe/src/expander/matcher.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/tt_iter.rs
  crates/parser/src/edition.rs
  crates/parser/src/lib.rs
  crates/parser/src/parser.rs
  crates/parser/src/tests.rs
  crates/parser/src/tests/prefix_entries.rs
  crates/span/Cargo.toml
  crates/span/src/lib.rs
  crates/span/src/map.rs
  crates/syntax/src/lib.rs
  crates/syntax/src/parsing.rs
  crates/syntax/src/parsing/reparsing.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-author

#17065 internal: Thread edition through to parsing/tt-to-syntax-tree routines for macros
  crates/base-db/src/lib.rs
  crates/cfg/src/tests.rs
  crates/hir-def/src/attr/tests.rs
  crates/hir-def/src/find_path.rs
  crates/hir-expand/src/builtin_fn_macro.rs
  crates/hir-expand/src/cfg_process.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-expand/src/fixup.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/snippet.rs
  crates/ide-db/src/imports/insert_use.rs
  crates/ide-db/src/imports/insert_use/tests.rs
  crates/ide-ssr/src/fragments.rs
  crates/ide/src/file_structure.rs
  crates/ide/src/folding_ranges.rs
  crates/ide/src/join_lines.rs
  crates/ide/src/matching_brace.rs
  crates/ide/src/syntax_tree.rs
  crates/ide/src/typing.rs
  crates/mbe/src/benchmark.rs
  crates/mbe/src/expander.rs
  crates/mbe/src/expander/matcher.rs
  crates/mbe/src/lib.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/syntax_bridge/tests.rs
  crates/rust-analyzer/src/cargo_target_spec.rs
  crates/rust-analyzer/src/cli/parse.rs
  crates/syntax/src/algo.rs
  crates/syntax/src/ast.rs
  crates/syntax/src/ast/edit_in_place.rs
  crates/syntax/src/ast/expr_ext.rs
  crates/syntax/src/ast/make.rs
  crates/syntax/src/fuzz.rs
  crates/syntax/src/hacks.rs
  crates/syntax/src/lib.rs
  crates/syntax/src/parsing/reparsing.rs
  crates/syntax/src/ptr.rs
  crates/syntax/src/tests.rs
Labels: S-waiting-on-review

#17069 minor: Fix `rustc_skip_array_during_method_dispatch` edition check
  crates/hir-ty/src/method_resolution.rs
Labels: S-waiting-on-review

#17070 internal: Remove unnecessay `GlobalState::send_hint_refresh_query` field
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#16813 Wrap/Unwrap cfg_attr
  crates/ide-assists/src/handlers/wrap_unwrap_cfg_attr.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-author

#16877 fix: Fix `impl Trait<Self>` causing stackoverflows
  Cargo.toml
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/tests/display_source_code.rs
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/promote_local_to_const.rs
  crates/ide-completion/src/completions/type.rs
  crates/ide-db/src/label.rs
  crates/ide-diagnostics/src/handlers/unresolved_field.rs
  crates/ide-diagnostics/src/handlers/unused_variables.rs
  crates/ide/src/hover/tests.rs
Labels: S-blocked

#17072 internal: Use `hir_fmt_args` everywhere in `hir_ty::display`
  crates/hir-ty/src/display.rs
Labels: S-waiting-on-review

#17073 Better inline preview for postfix completion
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/completions/postfix/format_like.rs
Labels: S-waiting-on-review

#17074 Add Static and Const highlighting token types
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/ide/src/syntax_highlighting/tags.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_general.html
  crates/ide/src/syntax_highlighting/tests.rs
  crates/rust-analyzer/src/lsp/semantic_tokens.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  editors/code/package.json
Labels: S-waiting-on-review

#17078 internal: Improve diagnostics performance
  crates/base-db/src/lib.rs
  crates/hir-def/src/data.rs
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/db.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/inhabitedness.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir/src/lib.rs
  crates/ide-diagnostics/src/handlers/missing_match_arms.rs
  crates/ide-diagnostics/src/lib.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
Labels: S-waiting-on-review

#17081 Revert #17073: Better inline preview for postfix completion
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/completions/postfix/format_like.rs
Labels: S-waiting-on-review

#17037 internal: improve `TokenSet` implementation and add reserved keywords
  crates/ide-assists/src/handlers/auto_import.rs
  crates/parser/src/syntax_kind/generated.rs
  crates/parser/src/token_set.rs
  xtask/src/codegen/grammar/ast_src.rs
Labels: S-waiting-on-review

#16639 internal : redesign rust-analyzer::config
  Cargo.lock
  crates/base-db/src/input.rs
  crates/ide/src/expand_macro.rs
  crates/ide/src/lib.rs
  crates/project-model/src/cfg_flag.rs
  crates/project-model/src/project_json.rs
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/diagnostics.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/rust-analyzer/src/reload.rs
  docs/user/generated_config.adoc
Labels: S-waiting-on-review

#17083 ide: improve ReferenceCategoryType
  Cargo.lock
  crates/ide-assists/src/handlers/extract_function.rs
  crates/ide-assists/src/handlers/remove_unused_imports.rs
  crates/ide-db/Cargo.toml
  crates/ide-db/src/search.rs
  crates/ide/src/highlight_related.rs
  crates/ide/src/references.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#17055 fix: Replace Just the variable name in Unused Variable Diagnostic Fix
  crates/ide-diagnostics/src/handlers/unused_variables.rs
Labels: S-waiting-on-author

#17092 minor: Update `per_query_memory_usage` query listing
  crates/hir/src/db.rs
  crates/ide-db/src/apply_change.rs
Labels: S-waiting-on-review

#17087 chore: fix a few spans without `.entered()`
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/inhabitedness.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/hir/src/semantics/source_to_def.rs
  crates/ide-assists/src/handlers/add_missing_impl_members.rs
Labels: S-waiting-on-review

#17093 fix: VFS should not walk circular symlinks
  crates/vfs-notify/src/lib.rs
Labels: S-waiting-on-review

#17095 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-review

#16057 Render matched macro arm on hover of macro calls
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/declarative.rs
  crates/hir/src/semantics.rs
  crates/ide/src/hover.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/static_index.rs
  crates/mbe/src/benchmark.rs
  crates/mbe/src/expander.rs
  crates/mbe/src/lib.rs
  crates/span/src/map.rs
Labels: S-waiting-on-author

#17105 Make test harness arguments configurable and not `--nocapture`.
  crates/rust-analyzer/src/cargo_target_spec.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#16726 internal: Remove rustc core test cfg hacks
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-blocked

#17094 feat: Add convert From to TryFrom assist
  crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
  crates/ide-assists/src/lib.rs
  crates/ide-assists/src/tests/generated.rs
Labels: S-waiting-on-author

#17024 fix: handle escaped chars in doc comments
  crates/hir-def/src/attr.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-expand/src/attrs.rs
  crates/ide-db/src/documentation.rs
  crates/syntax/src/lib.rs
Labels: S-waiting-on-author

#17108 internal: Cleanup cfg and env handling in project-model
  crates/base-db/src/input.rs
  crates/cfg/src/lib.rs
  crates/load-cargo/src/lib.rs
  crates/proc-macro-api/src/lib.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/cfg.rs
  crates/project-model/src/env.rs
  crates/project-model/src/lib.rs
  crates/project-model/src/project_json.rs
  crates/project-model/src/rustc_cfg.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/project-model/test_data/output/cargo_hello_world_project_model.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt
  crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt
  crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/reload.rs
  crates/test-fixture/src/lib.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#17110 Cargo script mvp
  crates/load-cargo/src/lib.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
Labels: S-waiting-on-review

#17114 minor: Add in-rust-tree feature to hir-expand
  crates/hir-def/Cargo.toml
  crates/hir-expand/Cargo.toml
  crates/hir-expand/src/lib.rs
  crates/hir-ty/Cargo.toml
  crates/hir/Cargo.toml
  crates/load-cargo/Cargo.toml
  crates/rust-analyzer/Cargo.toml
Labels: S-waiting-on-review

#17118 feat: Allow rust files to be used linkedProjects
  crates/base-db/src/lib.rs
  crates/hir/src/semantics/source_to_def.rs
  crates/ide-db/src/prime_caches.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/lib.rs
  crates/project-model/src/manifest_path.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/progress_report.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/crate_graph.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  crates/rust-analyzer/tests/slow-tests/support.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#17119 internal: Extract common fields out of `ProjectWorkspace` variants
  crates/flycheck/src/lib.rs
  crates/load-cargo/src/lib.rs
  crates/project-model/src/build_scripts.rs
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/env.rs
  crates/project-model/src/lib.rs
  crates/project-model/src/manifest_path.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/reload.rs
  crates/rust-analyzer/tests/crate_graph.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
Labels: S-waiting-on-review

#17115 Try to generate more meaningful names in json converter
  crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
Labels: S-waiting-on-review

#16938 Implement `BeginPanic` handling in const eval
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/tests.rs
  crates/hir-ty/src/chalk_ext.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/shim.rs
  crates/hir-ty/src/mir/eval/tests.rs
  crates/ide-diagnostics/src/tests.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_default_library.html
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/syntax/rust.ungram
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-author

#17025 internal: Use josh for subtree syncs
  Cargo.lock
  crates/rust-analyzer/tests/slow-tests/tidy.rs
  docs/dev/README.md
  rust-version
  xtask/Cargo.toml
  xtask/src/flags.rs
  xtask/src/main.rs
  xtask/src/release.rs
Labels: S-waiting-on-review

#17102 chore: add some `tracing` to project loading
  Cargo.lock
  crates/load-cargo/src/lib.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/main_loop.rs
  crates/vfs/Cargo.toml
  crates/vfs/src/lib.rs
Labels: S-waiting-on-review

#17131 different error code of "no such field" error based on variant type
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir/src/diagnostics.rs
  crates/ide-diagnostics/src/handlers/no_such_field.rs
Labels: S-waiting-on-review

#17021 Support hovering limits for adts
  crates/hir/src/display.rs
  crates/ide/src/hover.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#17134 internal: Don't render unknown lifetimes when rendering generic args
  crates/hir-ty/src/display.rs
  crates/hir-ty/src/tests/coercion.rs
  crates/hir-ty/src/tests/diagnostics.rs
  crates/hir-ty/src/tests/display_source_code.rs
  crates/hir-ty/src/tests/macros.rs
  crates/hir-ty/src/tests/method_resolution.rs
  crates/hir-ty/src/tests/never_type.rs
  crates/hir-ty/src/tests/patterns.rs
  crates/hir-ty/src/tests/regression.rs
  crates/hir-ty/src/tests/simple.rs
  crates/hir-ty/src/tests/traits.rs
  crates/ide-assists/src/handlers/extract_function.rs
  crates/ide-completion/src/tests/predicate.rs
  crates/ide-completion/src/tests/type_pos.rs
  crates/ide/src/inlay_hints/bind_pat.rs
Labels: S-waiting-on-review

#17135 fix: Fix expression scopes not being calculated for inline consts
  crates/hir-def/src/body/scope.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-ty/src/tests/simple.rs
  crates/ide-assists/src/handlers/reorder_impl_items.rs
  crates/ide-db/src/symbol_index.rs
  crates/salsa/src/lru.rs
  crates/salsa/src/revision.rs
Labels: S-waiting-on-review

#17143 internal: Show workspace info in the status bar
  .git-blame-ignore-revs
  crates/hir/src/semantics.rs
  crates/load-cargo/src/lib.rs
  crates/proc-macro-api/src/lib.rs
  crates/proc-macro-api/src/process.rs
  crates/project-model/src/project_json.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/reload.rs
  docs/dev/lsp-extensions.md
  editors/code/src/ctx.ts
  editors/code/src/lsp_ext.ts
Labels: S-waiting-on-review

#17145 fix: Fix source roots not always being created when necessary
  crates/rust-analyzer/src/global_state.rs
Labels: S-waiting-on-review

#17150 internal: add no-new-root check to josh pull
  rust-version
  xtask/src/release.rs
Labels: S-waiting-on-review

#17151 fix: Fix attributes on generic parameters colliding in item tree
  crates/hir-def/src/data.rs
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/generics.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/item_tree/tests.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/tests/regression.rs
  crates/hir-ty/src/tests/traits.rs
Labels: S-waiting-on-review

#17153 fix: Fix doc comment desugaring for proc-macros
  crates/cfg/src/tests.rs
  crates/hir-def/src/attr/tests.rs
  crates/hir-def/src/macro_expansion_tests/proc_macros.rs
  crates/hir-expand/src/attrs.rs
  crates/hir-expand/src/builtin_derive_macro.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-expand/src/eager.rs
  crates/hir-expand/src/fixup.rs
  crates/mbe/src/benchmark.rs
  crates/mbe/src/lib.rs
  crates/mbe/src/syntax_bridge.rs
  crates/mbe/src/syntax_bridge/tests.rs
  crates/rust-analyzer/src/cargo_target_spec.rs
Labels: S-waiting-on-review

#17157 fix: Don't retry position relient requests and version resolve data
  crates/rust-analyzer/src/dispatch.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/from_proto.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#17144 manual: remove suggestion of rust-project.json example
  docs/user/manual.adoc
Labels: S-waiting-on-review

#17161 fix: discard path when the path is invalid
  crates/vfs-notify/src/lib.rs
Labels: S-waiting-on-review

#17138 feature: Make generate function assist generate a function as a constructor if the generated function has the name "new" and is an asscociated function.
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/generate_function.rs
Labels: S-waiting-on-review

#17160 Implement creating generics for impl traits in associated types
  crates/hir-def/src/generics.rs
  crates/hir-def/src/lower.rs
  crates/hir-def/src/path/lower.rs
  crates/hir-def/src/resolver.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/tests/traits.rs
Labels: S-waiting-on-review

#17147 docs: Fix typo in VS Code setting description
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-author

#17148 fix: Tracing span names should match function names
  crates/base-db/src/change.rs
  crates/base-db/src/lib.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/hir/src/semantics/source_to_def.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/literal.rs
  crates/ide-completion/src/render/macro_.rs
  crates/ide-db/src/imports/import_assets.rs
  crates/ide-db/src/imports/insert_use.rs
  crates/ide-db/src/prime_caches.rs
  crates/ide/src/inlay_hints.rs
  crates/load-cargo/src/lib.rs
  crates/proc-macro-api/src/lib.rs
  crates/rust-analyzer/src/cli/parse.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/handlers/request.rs
Labels: S-waiting-on-author
