Repository rust-lang/rust-analyzer, pull requests merged in 2025-01, with the labels that each got.

#18757 feat: support updating snapshot tests with codelens/hovering/runnables
  crates/hir/src/lib.rs
  crates/ide/src/annotations.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/runnables.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  docs/dev/lsp-extensions.md
  docs/user/generated_config.adoc
  editors/code/package.json
  editors/code/src/commands.ts
  editors/code/src/config.ts
Labels: S-waiting-on-review

#18809 internal: Do not render closure ids in hover messages
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/inlay_hints/binding_mode.rs
Labels: S-waiting-on-review

#18179 feat: Allow excluding specific traits from completion
  crates/hir-ty/src/method_resolution.rs
  crates/hir/src/attrs.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/completions/expr.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/config.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/lib.rs
  crates/ide-completion/src/snippet.rs
  crates/ide-completion/src/tests.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-completion/src/tests/flyimport.rs
  crates/ide-completion/src/tests/special.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-author

#18817 fix: Fix flycheck cancellations leaving stale errors
  crates/rust-analyzer/src/flycheck.rs
Labels: S-waiting-on-review

#18819 fix: Fix overflow detection in MIR evaluation
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/eval/tests.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#18820 Fix no space insert before and after if value is only spaces
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#18822 allow targetDir to be an absolute path
  crates/rust-analyzer/src/config.rs
Labels: S-waiting-on-review

#18825 minor: Encode TraitData bools as bitflags
  crates/hir-def/src/data.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/dyn_compatibility.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir/src/display.rs
  crates/hir/src/lib.rs
Labels: S-waiting-on-review

#18826 fix: Clear flycheck diagnostics per package properly
  crates/rust-analyzer/src/flycheck.rs
Labels: S-waiting-on-review

#18827 minor: Honor `CARGO_TARGET_DIR` for cargo target dir config
  crates/rust-analyzer/src/config.rs
Labels: S-waiting-on-review

#18828 minor: Add description field to edition manifest
  crates/edition/Cargo.toml
Labels: S-waiting-on-review

#18829 Disable rustc_test metrics again
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#18806 fix: Deduplicate crate graph
  crates/base-db/src/input.rs
  crates/project-model/src/env.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/project-model/test_data/output/rust_project_cfg_groups.txt
  crates/project-model/test_data/regex-metadata.json
  crates/project-model/test_data/ripgrep-metadata.json
Labels: S-waiting-on-review

#18831 Fix metrics workflow
  .github/workflows/metrics.yaml
Labels: S-waiting-on-review

#18835 Hide synthetic locals from completions
  crates/ide-completion/src/completions/expr.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/tests/expression.rs
Labels: S-waiting-on-review

#18821 feat: Support the new `CoercePointee` derive
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-def/src/macro_expansion_tests/mod.rs
  crates/hir-expand/src/builtin/derive_macro.rs
  crates/ide-assists/src/handlers/move_bounds.rs
  crates/ide/src/expand_macro.rs
  crates/intern/src/symbol/symbols.rs
  crates/syntax/src/ast/make.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#18841 fix: Fix relative .cargo env vars not working
  crates/project-model/src/env.rs
Labels: S-waiting-on-review

#18843 fix: Handle newstyle `rustc_intrinsic` safety correctly
  crates/hir-ty/src/utils.rs
  crates/ide-diagnostics/src/handlers/missing_unsafe.rs
Labels: S-waiting-on-review

#18845 fix: Fix flycheck getting confused which package to check
  crates/rust-analyzer/src/flycheck.rs
  crates/rust-analyzer/src/global_state.rs
  crates/rust-analyzer/src/handlers/notification.rs
  crates/rust-analyzer/src/target_spec.rs
Labels: S-waiting-on-review

#18836 fix: Be more permissive with completion resolve data
  crates/rust-analyzer/src/lsp/ext.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#18848 fix: Fix non-cargo flychecks immediately clearing received diagnostics
  crates/rust-analyzer/src/flycheck.rs
Labels: S-waiting-on-review

#18852 fix: Fix a bug that was caused by fixup reversing
  crates/hir-expand/src/fixup.rs
  crates/ide/src/inlay_hints.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#18858 fix: clear diagnostics on cancel unconditionally
  crates/rust-analyzer/src/flycheck.rs
Labels: S-waiting-on-review

#18853 Fix case where completion inside macro that expands to `#[test]` was unavailable
  crates/hir-def/src/nameres/collector.rs
  crates/hir/src/semantics.rs
  crates/ide-completion/src/tests/item.rs
Labels: S-waiting-on-review

#18832 fix: do not offer completions within macro strings
  crates/ide-completion/src/context/analysis.rs
  crates/ide-completion/src/tests/attribute.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#18864 fix: Fix diagnostics not clearing between flychecks
  crates/rust-analyzer/src/flycheck.rs
Labels: S-waiting-on-review

#18788 Remove `rust-analyzer.cargo.sysrootQueryMetadata` config again
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/lib.rs
  crates/project-model/src/sysroot.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/cli/flags.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/tests/slow-tests/main.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18867 internal: target-triple -> target-tuple + version fetching cleanup
  crates/project-model/src/lib.rs
  crates/project-model/src/toolchain_info/rustc_cfg.rs
  crates/project-model/src/toolchain_info/target_data_layout.rs
  crates/project-model/src/toolchain_info/target_tuple.rs
  crates/project-model/src/toolchain_info/version.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/flycheck.rs
  docs/user/generated_config.adoc
  docs/user/manual.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18870 Drop unnecessary tracing::warn
  crates/mbe/src/expander/transcriber.rs
Labels: S-waiting-on-review

#18874 minor: Sync from downstream
  crates/hir-expand/src/inert_attr_macro.rs
  rust-version
Labels: S-waiting-on-review

#18877 fix: Fix a bug with missing binding in MBE
  crates/ide-diagnostics/src/tests.rs
  crates/ide-diagnostics/src/tests/overly_long_real_world_cases.rs
  crates/mbe/src/expander/transcriber.rs
Labels: S-waiting-on-review

#18882 minor: Fix `test-fixture` autopublishing
  Cargo.toml
  crates/test-fixture/Cargo.toml
Labels: S-waiting-on-review

#18855 internal: Migrate `if let` replacement assists to `SyntaxEditor`
  crates/ide-assists/src/handlers/add_missing_match_arms.rs
  crates/ide-assists/src/handlers/apply_demorgan.rs
  crates/ide-assists/src/handlers/bool_to_enum.rs
  crates/ide-assists/src/handlers/convert_closure_to_fn.rs
  crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
  crates/ide-assists/src/handlers/convert_while_to_loop.rs
  crates/ide-assists/src/handlers/extract_function.rs
  crates/ide-assists/src/handlers/move_guard.rs
  crates/ide-assists/src/handlers/remove_dbg.rs
  crates/ide-assists/src/handlers/replace_if_let_with_match.rs
  crates/ide-assists/src/handlers/replace_let_with_if_let.rs
  crates/ide-assists/src/handlers/replace_try_expr_with_match.rs
  crates/ide-assists/src/handlers/unmerge_match_arm.rs
  crates/ide-assists/src/handlers/unwrap_block.rs
  crates/ide-assists/src/utils.rs
  crates/ide-assists/src/utils/gen_trait_fn_body.rs
  crates/ide-assists/src/utils/ref_field_expr.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/syntax/src/ast/edit.rs
  crates/syntax/src/ast/expr_ext.rs
  crates/syntax/src/ast/make.rs
  crates/syntax/src/ast/syntax_factory/constructors.rs
  crates/syntax/src/syntax_editor.rs
Labels: S-waiting-on-review

#18884 fix: Fix `env`/`option_env` macro check disregarding macro_rules definitions
  crates/hir/src/lib.rs
  crates/ide-completion/src/completions/env_vars.rs
Labels: S-waiting-on-review

#18524 internal: Migrate `(un)wrap_return_type` assists to use `SyntaxEditor`
  crates/ide-assists/src/handlers/add_turbo_fish.rs
  crates/ide-assists/src/handlers/unwrap_return_type.rs
  crates/ide-assists/src/handlers/wrap_return_type.rs
  crates/ide-assists/src/utils/gen_trait_fn_body.rs
  crates/syntax/src/ast/make.rs
  crates/syntax/src/ast/syntax_factory/constructors.rs
Labels: S-waiting-on-review

#18887 refactor test helpers within ide-completions
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/completions/extern_abi.rs
  crates/ide-completion/src/completions/format_string.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-completion/src/completions/keyword.rs
  crates/ide-completion/src/completions/lifetime.rs
  crates/ide-completion/src/completions/mod_.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/tests.rs
  crates/ide-completion/src/tests/attribute.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-completion/src/tests/fn_param.rs
  crates/ide-completion/src/tests/item.rs
  crates/ide-completion/src/tests/item_list.rs
  crates/ide-completion/src/tests/pattern.rs
  crates/ide-completion/src/tests/predicate.rs
  crates/ide-completion/src/tests/proc_macros.rs
  crates/ide-completion/src/tests/record.rs
  crates/ide-completion/src/tests/special.rs
  crates/ide-completion/src/tests/type_pos.rs
  crates/ide-completion/src/tests/use_tree.rs
  crates/ide-completion/src/tests/visibility.rs
Labels: S-waiting-on-review

#18890 minor: Fixup macro error kinds
  crates/hir-expand/src/lib.rs
  crates/ide-diagnostics/src/handlers/macro_error.rs
Labels: S-waiting-on-review

#18861 fix: Make edition per-token, not per-file
  crates/edition/src/lib.rs
  crates/hir-def/src/body.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/expander.rs
  crates/hir-def/src/item_tree/tests.rs
  crates/hir-def/src/macro_expansion_tests/mbe.rs
  crates/hir-def/src/macro_expansion_tests/mod.rs
  crates/hir-def/src/macro_expansion_tests/proc_macros.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/resolver.rs
  crates/hir-expand/src/builtin/derive_macro.rs
  crates/hir-expand/src/builtin/fn_macro.rs
  crates/hir-expand/src/builtin/quote.rs
  crates/hir-expand/src/db.rs
  crates/hir-expand/src/declarative.rs
  crates/hir-expand/src/files.rs
  crates/hir-expand/src/fixup.rs
  crates/hir-expand/src/hygiene.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-expand/src/name.rs
  crates/hir/src/attrs.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/ide-diagnostics/src/handlers/no_such_field.rs
  crates/mbe/src/lib.rs
  crates/mbe/src/tests.rs
  crates/proc-macro-api/src/legacy_protocol/msg.rs
  crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs
  crates/proc-macro-srv/src/tests/mod.rs
  crates/proc-macro-srv/src/tests/utils.rs
  crates/span/src/hygiene.rs
  crates/span/src/map.rs
  crates/syntax-bridge/src/lib.rs
  crates/syntax-bridge/src/to_parser_input.rs
Labels: S-waiting-on-review

#18885 refactor: struct holding cargo cfgs settings
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18880 Add config setting which allows adding additional include paths to the VFS.
  crates/project-model/src/cargo_workspace.rs
  crates/project-model/src/tests.rs
  crates/project-model/src/workspace.rs
  crates/rust-analyzer/src/cli/rustc_tests.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18889 fix: Fix actual token lookup in completion's `expand()`
  crates/ide-completion/src/context/analysis.rs
Labels: S-waiting-on-review

#18899 fix: Fix another issue with fixup reversing
  crates/hir-expand/src/builtin/quote.rs
  crates/hir-expand/src/fixup.rs
  crates/ide/src/inlay_hints.rs
  crates/test-fixture/src/lib.rs
Labels: S-waiting-on-review

#18813 feat: Add a new and improved syntax tree view
  crates/ide/src/lib.rs
  crates/ide/src/syntax_tree.rs
  crates/ide/src/view_syntax_tree.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/main_loop.rs
  docs/dev/lsp-extensions.md
  editors/code/package.json
  editors/code/src/ast_inspector.ts
  editors/code/src/commands.ts
  editors/code/src/config.ts
  editors/code/src/ctx.ts
  editors/code/src/lsp_ext.ts
  editors/code/src/main.ts
  editors/code/src/syntax_tree_provider.ts
Labels: S-waiting-on-review

#18902 internal: Add Definition::Crate
  crates/hir/src/attrs.rs
  crates/hir/src/display.rs
  crates/ide-db/src/defs.rs
  crates/ide-db/src/documentation.rs
  crates/ide-db/src/rename.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/moniker.rs
  crates/ide/src/navigation_target.rs
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/ide/src/syntax_highlighting/inject.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_block_mod_items.html
  crates/ide/src/syntax_highlighting/test_data/highlight_const.html
  crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
  crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
  crates/ide/src/syntax_highlighting/test_data/highlight_issue_18089.html
  crates/ide/src/syntax_highlighting/test_data/highlight_keywords_2015.html
  crates/ide/src/syntax_highlighting/test_data/highlight_keywords_2018.html
  crates/ide/src/syntax_highlighting/test_data/highlight_keywords_2021.html
  crates/ide/src/syntax_highlighting/test_data/highlight_keywords_2024.html
  crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
Labels: S-waiting-on-review

#18900 fix: Do not compute `prettify_macro_expansion()` unless the "Inline macro" assist has actually been invoked
  crates/ide-assists/src/handlers/inline_macro.rs
Labels: S-waiting-on-review

#18903 Implement implicit sized bound inlay hints
  crates/ide-assists/src/handlers/inline_macro.rs
  crates/ide-db/src/famous_defs.rs
  crates/ide/src/inlay_hints.rs
  crates/ide/src/inlay_hints/bounds.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/ide/src/static_index.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18904 Improve hover module path rendering
  crates/hir/src/lib.rs
  crates/ide-db/src/defs.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_attributes.html
Labels: S-waiting-on-review

#18907 Implement `#[rust_analyzer::skip]` for bodies
  crates/hir-def/src/attr.rs
  crates/hir-def/src/body/lower.rs
  crates/hir-def/src/body/tests.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-ty/src/tests/simple.rs
  crates/ide/src/goto_type_definition.rs
  crates/intern/src/symbol/symbols.rs
Labels: S-waiting-on-review

#18913 minor: Fix grammar in doc comments
  crates/base-db/src/lib.rs
  crates/ide/src/lib.rs
Labels: S-waiting-on-review

#18920 fix: Fix `ref` text edit for binding mode hints
  crates/ide/src/inlay_hints/binding_mode.rs
Labels: S-waiting-on-review

#18921 internal: Compute inlay hint text edits lazily
  crates/ide/src/inlay_hints.rs
  crates/ide/src/inlay_hints/adjustment.rs
  crates/ide/src/inlay_hints/bind_pat.rs
  crates/ide/src/inlay_hints/binding_mode.rs
  crates/ide/src/inlay_hints/closure_ret.rs
  crates/ide/src/inlay_hints/discriminant.rs
  crates/ide/src/inlay_hints/extern_block.rs
  crates/ide/src/inlay_hints/implicit_static.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#18923 internal: Compute inlay hint tooltips lazily
  crates/ide/src/inlay_hints.rs
  crates/ide/src/inlay_hints/adjustment.rs
  crates/ide/src/inlay_hints/discriminant.rs
  crates/ide/src/inlay_hints/implicit_drop.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#18933 fix: Update `notify` to `8.0.0`
  Cargo.lock
  crates/vfs-notify/Cargo.toml
Labels: S-waiting-on-review

#18937 Hide syntax tree view by default
  editors/code/package.json
Labels: S-waiting-on-review

#18917 feat: Add dereferencing autocomplete
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/lib.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/function.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/lib.rs
Labels: S-waiting-on-review

#18925 feat: Render type parameter projection target bounds in inlays
  crates/hir-ty/src/display.rs
  crates/ide/src/inlay_hints/bind_pat.rs
Labels: S-waiting-on-review

#18939 Flip on typing config to be opt-in, better defaults
  crates/hir/src/semantics.rs
  crates/ide-db/src/search.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/handlers/request.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18940 fix: Fix semantics not always correctly caching file roots
  crates/hir/src/semantics.rs
  crates/hir/src/semantics/source_to_def.rs
Labels: S-waiting-on-review

#18897 fix: Make test_runner::TestState::stdout optional to fix parsing cargo test json output
  crates/rust-analyzer/src/test_runner.rs
Labels: S-waiting-on-review

#18944 update chalk, fixing trait upcasting
  Cargo.lock
  Cargo.toml
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
Labels: S-waiting-on-review

#18927 feat: Add smart completions that skip `await` or `iter()` and `into_iter()`
  crates/hir/src/lib.rs
  crates/ide-completion/src/completions.rs
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/function.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#18946 feat: show go-to-type-def actions for func param and trait bound when hovering
  crates/ide/src/hover.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#18949 Partially back out "fix: Fix sourceroot construction for virtual manifests"
  crates/load-cargo/src/lib.rs
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#18950 Generalize some type walking in hover type actions
  crates/hir/src/lib.rs
  crates/ide-db/src/defs.rs
  crates/ide/src/hover.rs
Labels: S-waiting-on-review

#18951 Add missing `#[rust_analyzer::rust_fixture]` annotations
  crates/hir/src/lib.rs
  crates/ide-assists/src/handlers/destructure_tuple_binding.rs
  crates/ide-assists/src/handlers/remove_dbg.rs
  crates/ide-assists/src/tests.rs
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/tests.rs
  crates/ide-db/src/imports/insert_use/tests.rs
  crates/ide-diagnostics/src/tests.rs
  crates/ide/src/join_lines.rs
  crates/ide/src/rename.rs
  crates/ide/src/typing.rs
  crates/ide/src/typing/on_enter.rs
Labels: S-waiting-on-review

#18953 Fix `debug_assertions` broken in 1c5a125
  crates/rust-analyzer/src/config.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18952 feat: complete raw, const keyword
  crates/hir-def/src/body/lower.rs
  crates/ide-completion/src/completions/expr.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/context/analysis.rs
  crates/ide-completion/src/tests/expression.rs
  crates/parser/src/grammar/expressions.rs
  crates/parser/test_data/parser/inline/ok/ref_expr.rast
  crates/parser/test_data/parser/inline/ok/ref_expr.rs
Labels: S-waiting-on-review

#18908 Fix: Detect missing errors for } braces before else in let...else statements
  crates/parser/src/event.rs
  crates/parser/src/grammar/expressions.rs
  crates/parser/src/parser.rs
  crates/parser/test_data/parser/err/0056_let_else_right_curly_brace_struct.rast
  crates/parser/test_data/parser/err/0056_let_else_right_curly_brace_struct.rs
  crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_arithmetic.rast
  crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_arithmetic.rs
  crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_format_args.rast
  crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_format_args.rs
  crates/parser/test_data/parser/err/0058_let_else_right_curly_brace_range.rast
  crates/parser/test_data/parser/err/0058_let_else_right_curly_brace_range.rs
  crates/parser/test_data/parser/err/0059_let_else_right_curly_brace_closure.rast
  crates/parser/test_data/parser/err/0059_let_else_right_curly_brace_closure.rs
  crates/parser/test_data/parser/err/0060_let_else_right_curly_brace_unary.rast
  crates/parser/test_data/parser/err/0060_let_else_right_curly_brace_unary.rs
  crates/parser/test_data/parser/err/0061_let_else_right_curly_brace_do_yeet.rast
  crates/parser/test_data/parser/err/0061_let_else_right_curly_brace_do_yeet.rs
  crates/parser/test_data/parser/err/0062_let_else_right_curly_brace_become.rast
  crates/parser/test_data/parser/err/0062_let_else_right_curly_brace_become.rs
  crates/parser/test_data/parser/err/0063_let_else_right_curly_brace_reference.rast
  crates/parser/test_data/parser/err/0063_let_else_right_curly_brace_reference.rs
  crates/parser/test_data/parser/err/0064_let_else_right_curly_brace_assignment.rast
  crates/parser/test_data/parser/err/0064_let_else_right_curly_brace_assignment.rs
Labels: S-waiting-on-review

#18963 add missing `Win32_Foundation` feature
  crates/profile/Cargo.toml
Labels: S-waiting-on-review

#18968 fix: `cargo rustc --print` needs `unstable-options`
  crates/project-model/src/toolchain_info/rustc_cfg.rs
Labels: S-waiting-on-review

#18957 Update syntax tree viewer docs
  docs/dev/README.md
Labels: S-waiting-on-review

#18966 minor: Bump `windows-sys`
  Cargo.lock
  crates/profile/Cargo.toml
  crates/rust-analyzer/Cargo.toml
  crates/stdx/Cargo.toml
Labels: S-waiting-on-review

#18980 minor: Sync from downstream
  Cargo.lock
  Cargo.toml
  crates/hir-ty/src/layout.rs
  rust-version
Labels: S-waiting-on-review

#18981 proc-macro-srv: make usage of RTLD_DEEPBIND portable
  Cargo.lock
  crates/proc-macro-srv/Cargo.toml
  crates/proc-macro-srv/src/dylib.rs
Labels: S-waiting-on-review

#18976 fix: Fix a bug where enum variants were not considered properly in type ns resolution
  crates/hir-def/src/resolver.rs
  crates/hir-ty/src/lower.rs
  crates/ide-diagnostics/src/handlers/generic_args_prohibited.rs
Labels: S-waiting-on-review, S-needs-backporting

#18972 lsp-server: Drop outgoing messages on background thread
  lib/lsp-server/src/msg.rs
  lib/lsp-server/src/socket.rs
  lib/lsp-server/src/stdio.rs
Labels: S-waiting-on-review

#18982 Extract variable assist triggers less eagerly
  crates/ide-assists/src/assist_context.rs
  crates/ide-assists/src/handlers/extract_variable.rs
Labels: S-waiting-on-review

#18934 feat: Add the ability to jump from `into` to `from` definitions
  crates/hir-expand/src/mod_path.rs
  crates/hir/src/semantics.rs
  crates/hir/src/source_analyzer.rs
  crates/ide/src/goto_definition.rs
  crates/intern/src/symbol/symbols.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#18967 Properly record meaningful imports as re-exports in symbol index
  Cargo.lock
  Cargo.toml
  crates/hir-def/src/data.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/lang_item.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/visibility.rs
  crates/hir-expand/src/name.rs
  crates/hir-ty/src/chalk_db.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/tests.rs
  crates/hir/Cargo.toml
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/hir/src/semantics/child_by_source.rs
  crates/hir/src/symbols.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/tests/flyimport.rs
  crates/ide-db/src/imports/import_assets.rs
  crates/ide-db/src/items_locator.rs
  crates/ide-db/src/symbol_index.rs
  crates/ide-db/src/test_data/test_symbol_index_collection.txt
  crates/ide/src/navigation_target.rs
Labels: S-waiting-on-review

#18984 internal: Move dual blanket impl logic from source analyzer to goto_def
  crates/hir-def/src/lib.rs
  crates/hir-expand/src/name.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/hir/src/source_analyzer.rs
  crates/ide-db/src/famous_defs.rs
  crates/ide/src/goto_definition.rs
  crates/intern/src/symbol/symbols.rs
Labels: S-waiting-on-review

#18989 fix: Only refresh syntax tree view when the active document changes
  editors/code/src/ctx.ts
Labels: S-waiting-on-review

#18977 fix: Fix missing upmapping in trait impls completion
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-completion/src/context/analysis.rs
Labels: S-waiting-on-review

#18986 Goto `Display::fmt` when invoked on `to_string`
  crates/hir/src/semantics.rs
  crates/ide-db/src/famous_defs.rs
  crates/ide/src/goto_definition.rs
  crates/intern/src/symbol/symbols.rs
Labels: S-waiting-on-review

#18990 internal: Cleanup `Name` string rendering
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/nameres/mod_resolution.rs
  crates/hir-expand/src/mod_path.rs
  crates/hir-expand/src/name.rs
  crates/hir-ty/src/diagnostics/decl_check.rs
  crates/hir-ty/src/infer/closure.rs
  crates/ide-assists/src/handlers/convert_bool_then.rs
  crates/ide-assists/src/handlers/convert_closure_to_fn.rs
  crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
  crates/ide-assists/src/handlers/fix_visibility.rs
  crates/ide-assists/src/handlers/move_from_mod_rs.rs
  crates/ide-assists/src/handlers/move_module_to_file.rs
  crates/ide-assists/src/handlers/move_to_mod_rs.rs
  crates/ide-assists/src/handlers/qualify_path.rs
  crates/ide-assists/src/handlers/reorder_fields.rs
  crates/ide-assists/src/handlers/reorder_impl_items.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-completion/src/completions/mod_.rs
  crates/ide-completion/src/context/analysis.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/const_.rs
  crates/ide-completion/src/render/function.rs
  crates/ide-completion/src/render/literal.rs
  crates/ide-completion/src/render/macro_.rs
  crates/ide-completion/src/render/pattern.rs
  crates/ide-completion/src/render/type_alias.rs
  crates/ide-completion/src/render/union_literal.rs
  crates/ide-db/src/defs.rs
  crates/ide-db/src/famous_defs.rs
  crates/ide-db/src/rename.rs
  crates/ide-db/src/search.rs
  crates/ide-db/src/ty_filter.rs
  crates/ide-diagnostics/src/handlers/unlinked_file.rs
  crates/ide/src/doc_links.rs
  crates/ide/src/inlay_hints/param_name.rs
  crates/ide/src/rename.rs
  crates/intern/src/symbol/symbols.rs
Labels: S-waiting-on-review

#18988 fix: Sort completion items that skip `await` and `iter()` behind those that don't
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/render/function.rs
Labels: S-waiting-on-review

#18878 manual: Document all rust-project.json fields
  crates/project-model/src/project_json.rs
  docs/user/manual.adoc
Labels: S-waiting-on-review

#19004 increase `AUTODEREF_RECURSION_LIMIT` to 20
  crates/hir-ty/src/autoderef.rs
Labels: S-waiting-on-review

#19014 Check cfg when collecting macro defs
  crates/hir-def/src/body/lower.rs
Labels: S-waiting-on-review

#19016 fix: Fix `ItemScope` not recording glob imports
  crates/hir-def/src/body/tests/block.rs
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/nameres/tests.rs
  crates/hir-def/src/nameres/tests/globs.rs
  crates/hir-def/src/nameres/tests/macros.rs
  crates/hir-def/src/per_ns.rs
  crates/hir-def/src/resolver.rs
  crates/hir/src/symbols.rs
  crates/ide-db/src/symbol_index.rs
Labels: S-waiting-on-review

#18993 feat: Provide a config to control auto-insertion of `await` and `iter()`
  crates/ide-completion/src/completions/dot.rs
  crates/ide-completion/src/config.rs
  crates/ide-completion/src/tests.rs
  crates/rust-analyzer/src/config.rs
  crates/rust-analyzer/src/integrated_benchmarks.rs
  docs/user/generated_config.adoc
  editors/code/package.json
Labels: S-waiting-on-review

#18994 internal: Treat cfg fetching failures as a warning
  crates/project-model/src/toolchain_info/rustc_cfg.rs
Labels: S-waiting-on-review

#19017 fix: Fix flycheck panicking with "once" invocation strategy
  crates/rust-analyzer/src/flycheck.rs
  crates/rust-analyzer/src/handlers/notification.rs
Labels: S-waiting-on-review

#19012 feat: Implement `arbitrary-self-types`
  crates/hir-def/src/lang_item.rs
  crates/hir-ty/src/autoderef.rs
  crates/hir-ty/src/infer/coerce.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/method_resolution.rs
  crates/hir-ty/src/tests/method_resolution.rs
  crates/ide-completion/src/completions/dot.rs
  crates/intern/src/symbol/symbols.rs
  crates/test-utils/src/minicore.rs
Labels: S-waiting-on-review

#18991 Keep already computed inlay hint properties instead of late resolving them
  crates/hir/src/lib.rs
  crates/ide/src/inlay_hints.rs
  crates/ide/src/inlay_hints/bounds.rs
  crates/ide/src/inlay_hints/chaining.rs
  crates/ide/src/inlay_hints/closing_brace.rs
  crates/ide/src/inlay_hints/closure_captures.rs
  crates/ide/src/inlay_hints/generic_param.rs
  crates/ide/src/inlay_hints/implicit_drop.rs
  crates/ide/src/inlay_hints/param_name.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
Labels: S-waiting-on-review

#19018 internal: Record the use tree index in glob imports
  crates/hir-def/src/import_map.rs
  crates/hir-def/src/item_scope.rs
  crates/hir-def/src/nameres/collector.rs
  crates/hir-def/src/per_ns.rs
  crates/hir/src/symbols.rs
Labels: S-waiting-on-review

#19019 Explicitly add buildfiles when constructing ProjectFolders
  crates/load-cargo/src/lib.rs
  crates/project-model/src/workspace.rs
Labels: S-waiting-on-review

#19023 minor: Suggest better names when a type is a sequence
  crates/ide-assists/src/handlers/extract_variable.rs
  crates/ide-db/src/syntax_helpers/suggest_name.rs
Labels: S-waiting-on-review

#18973 Make niches into nices
  crates/ide/src/hover/render.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#19026 Only collect implicit visibile use symbols if they have renames
  crates/hir/src/symbols.rs
  crates/ide-db/src/test_data/test_symbol_index_collection.txt
Labels: S-waiting-on-review

#19028 fix: Fix flyimport not filtering via stability of import path
  crates/hir-def/src/find_path.rs
  crates/hir-def/src/lib.rs
  crates/hir-ty/src/display.rs
  crates/ide-assists/src/assist_config.rs
  crates/ide-completion/src/completions.rs
  crates/ide-completion/src/completions/expr.rs
  crates/ide-completion/src/completions/flyimport.rs
  crates/ide-completion/src/completions/postfix.rs
  crates/ide-completion/src/config.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/lib.rs
  crates/ide-completion/src/render.rs
  crates/ide-completion/src/snippet.rs
  crates/ide-completion/src/tests/flyimport.rs
  crates/ide-db/src/path_transform.rs
  crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/typed_hole.rs
  crates/ide-diagnostics/src/lib.rs
  crates/ide-ssr/src/matching.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-review

#19029 internal: Skip redundant path search in `resolve_completion_edits`
  crates/ide-completion/src/item.rs
  crates/ide-completion/src/lib.rs
  crates/ide/src/lib.rs
  crates/rust-analyzer/src/handlers/request.rs
  crates/rust-analyzer/src/lib.rs
  crates/rust-analyzer/src/lsp/ext.rs
  crates/rust-analyzer/src/lsp/to_proto.rs
  crates/syntax/src/ast/make.rs
  docs/dev/lsp-extensions.md
Labels: S-waiting-on-review

#18909 Use `strict_provenance`
  Cargo.lock
  Cargo.toml
  crates/intern/Cargo.toml
  crates/intern/src/symbol.rs
Labels: S-waiting-on-review

#19030 fix: Fix markdown horizontal ruler sometimes being treated as a heading
  crates/ide/src/hover.rs
  crates/ide/src/hover/tests.rs
Labels: S-waiting-on-review

#19020 fix: Prevent infinite recursion of bounds formatting
  crates/hir-ty/src/display.rs
  crates/ide/src/inlay_hints/bind_pat.rs
Labels: S-waiting-on-review

#19033 fix: Make proc_macro span's line & column 1-indexed, as documented
  crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs
  crates/proc-macro-srv/src/server_impl/token_id.rs
Labels: S-waiting-on-review

#19034 fix: Don't complete doc(hidden) enum variants and use trees
  crates/ide-completion/src/completions.rs
  crates/ide-completion/src/completions/item_list/trait_impl.rs
  crates/ide-completion/src/completions/use_.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/tests/expression.rs
  crates/ide-completion/src/tests/use_tree.rs
Labels: S-waiting-on-review

#19035 Update outdated permissions section in the README.md
  docs/dev/README.md
Labels: S-waiting-on-review

#19038 feat: Support RFC 2396
  crates/hir-def/src/data.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/display.rs
  crates/hir/src/lib.rs
  crates/hir/src/semantics.rs
  crates/hir/src/term_search/tactics.rs
  crates/ide-completion/src/context.rs
  crates/ide-completion/src/render/function.rs
  crates/ide-diagnostics/src/handlers/missing_unsafe.rs
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/intern/src/symbol/symbols.rs
Labels: S-waiting-on-review

#19037 fix: In completion's expand, consider recursion stop condition (when we're not inside a macro call anymore) *after* the recursive call instead of before it
  crates/ide-completion/src/context/analysis.rs
  crates/ide-completion/src/tests/expression.rs
Labels: S-waiting-on-review

#19036 Split out `ExpressionStore` from `Body`
  crates/hir-def/src/db.rs
  crates/hir-def/src/expr_store.rs
  crates/hir-def/src/expr_store/body.rs
  crates/hir-def/src/expr_store/lower.rs
  crates/hir-def/src/expr_store/lower/asm.rs
  crates/hir-def/src/expr_store/pretty.rs
  crates/hir-def/src/expr_store/scope.rs
  crates/hir-def/src/expr_store/tests.rs
  crates/hir-def/src/expr_store/tests/block.rs
  crates/hir-def/src/generics.rs
  crates/hir-def/src/hir.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/resolver.rs
  crates/hir-ty/src/consteval.rs
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/match_check.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/generics.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/diagnostics.rs
  crates/hir-ty/src/infer/pat.rs
  crates/hir-ty/src/infer/path.rs
  crates/hir-ty/src/lower.rs
  crates/hir-ty/src/mir.rs
  crates/hir-ty/src/mir/eval.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/pretty.rs
  crates/hir-ty/src/tests.rs
  crates/hir-ty/src/variance.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/from_id.rs
  crates/hir/src/lib.rs
  crates/hir/src/source_analyzer.rs
  crates/ide-db/src/defs.rs
  crates/ide-db/src/search.rs
  crates/ide/src/hover/render.rs
  crates/ide/src/signature_help.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-review

#19001 feat: Implement `default-field-values`
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/expr_store.rs
  crates/hir-def/src/expr_store/body.rs
  crates/hir-def/src/expr_store/lower.rs
  crates/hir-def/src/expr_store/pretty.rs
  crates/hir-def/src/hir.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-def/src/resolver.rs
  crates/hir-expand/src/builtin/derive_macro.rs
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/mutability.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/pretty.rs
  crates/hir-ty/src/tests.rs
  crates/hir-ty/src/tests/type_alias_impl_traits.rs
  crates/hir/src/from_id.rs
  crates/hir/src/lib.rs
  crates/hir/src/source_analyzer.rs
  crates/ide-db/src/defs.rs
  crates/ide-db/src/search.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/parser/src/grammar/expressions.rs
  crates/parser/src/grammar/items/adt.rs
  crates/parser/test_data/generated/runner.rs
  crates/parser/test_data/parser/inline/err/comma_after_default_values_syntax.rast
  crates/parser/test_data/parser/inline/err/comma_after_default_values_syntax.rs
  crates/parser/test_data/parser/inline/err/record_literal_before_ellipsis_recovery.rast
  crates/parser/test_data/parser/inline/err/record_literal_before_ellipsis_recovery.rs
  crates/parser/test_data/parser/inline/ok/record_field_default_values.rast
  crates/parser/test_data/parser/inline/ok/record_field_default_values.rs
  crates/parser/test_data/parser/inline/ok/record_lit.rast
  crates/parser/test_data/parser/inline/ok/record_lit.rs
  crates/parser/test_data/parser/inline/ok/struct_initializer_with_defaults.rast
  crates/parser/test_data/parser/inline/ok/struct_initializer_with_defaults.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
  crates/syntax/rust.ungram
  crates/syntax/src/ast/generated/nodes.rs
Labels: S-waiting-on-review

#19045 fix: Fix a missing standard token in semantic highlighting
  crates/rust-analyzer/src/lsp/semantic_tokens.rs
Labels: S-waiting-on-review

#19044 fix: Fix #[rustc_deprecated_safe_2024]
  crates/hir-def/src/data.rs
  crates/hir-def/src/expr_store/lower.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/lib.rs
  crates/hir-ty/src/utils.rs
  crates/hir/src/diagnostics.rs
  crates/hir/src/display.rs
  crates/hir/src/lib.rs
  crates/hir/src/source_analyzer.rs
  crates/hir/src/term_search/tactics.rs
  crates/ide-completion/src/render/function.rs
  crates/ide-diagnostics/src/handlers/missing_unsafe.rs
  crates/ide/src/syntax_highlighting.rs
  crates/ide/src/syntax_highlighting/format.rs
  crates/ide/src/syntax_highlighting/highlight.rs
Labels: S-waiting-on-review, S-needs-backporting

#19047 fix: Fix syntactic highlighting for renames
  crates/ide/src/syntax_highlighting/highlight.rs
  crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
  crates/ide/src/syntax_highlighting/tests.rs
Labels: S-waiting-on-review

#19049 minor: Remove duplicate method from `hir::Type`
  crates/hir/src/lib.rs
  crates/hir/src/term_search.rs
  crates/ide-assists/src/utils.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
Labels: S-waiting-on-review

#19052 Prioritize formatting thread tasks in main_loop
  crates/rust-analyzer/src/handlers/dispatch.rs
  crates/rust-analyzer/src/main_loop.rs
Labels: S-waiting-on-review

#19050 fix: Don't suggest `into_iter().method()` on iterators
  crates/hir/src/lib.rs
  crates/ide-completion/src/completions/dot.rs
Labels: S-waiting-on-review

#19051 fix: Report calling unsafe fn pointer as unsafe
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/ide-diagnostics/src/handlers/missing_unsafe.rs
Labels: S-waiting-on-review

#19055 Add FreeBSD as a target OS for TestDir to avoid warnings
  crates/rust-analyzer/tests/slow-tests/testdir.rs
Labels: S-waiting-on-review

#19061 Disable `Receiver` based autoderef temporarily
  crates/hir-ty/src/autoderef.rs
  crates/hir-ty/src/tests/method_resolution.rs
  crates/ide-completion/src/completions/dot.rs
Labels: S-waiting-on-review

#19057 Show status bar in RA output
  editors/code/package.json
Labels: S-waiting-on-review

#19056 fix: Properly handle CRLF line endings in the syntax tree view
  crates/ide/src/view_syntax_tree.rs
  editors/code/src/commands.ts
  editors/code/src/ctx.ts
  editors/code/src/syntax_tree_provider.ts
Labels: S-waiting-on-review

#19063 internal: backout `hir-*` changes from #19001
  crates/hir-def/src/data/adt.rs
  crates/hir-def/src/expr_store.rs
  crates/hir-def/src/expr_store/body.rs
  crates/hir-def/src/expr_store/lower.rs
  crates/hir-def/src/expr_store/pretty.rs
  crates/hir-def/src/hir.rs
  crates/hir-def/src/item_tree.rs
  crates/hir-def/src/item_tree/lower.rs
  crates/hir-def/src/item_tree/pretty.rs
  crates/hir-def/src/lib.rs
  crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
  crates/hir-def/src/resolver.rs
  crates/hir-expand/src/builtin/derive_macro.rs
  crates/hir-ty/src/diagnostics/expr.rs
  crates/hir-ty/src/diagnostics/unsafe_check.rs
  crates/hir-ty/src/infer.rs
  crates/hir-ty/src/infer/closure.rs
  crates/hir-ty/src/infer/expr.rs
  crates/hir-ty/src/infer/mutability.rs
  crates/hir-ty/src/mir/lower.rs
  crates/hir-ty/src/mir/pretty.rs
  crates/hir-ty/src/tests.rs
  crates/hir-ty/src/tests/type_alias_impl_traits.rs
  crates/hir/src/from_id.rs
  crates/hir/src/lib.rs
  crates/hir/src/source_analyzer.rs
  crates/ide-db/src/defs.rs
  crates/ide-db/src/search.rs
  crates/ide-diagnostics/src/handlers/missing_fields.rs
  crates/ide-diagnostics/src/handlers/type_mismatch.rs
  crates/rust-analyzer/src/cli/analysis_stats.rs
Labels: S-waiting-on-review

#19067 Update TentHash to version 1.0
  Cargo.lock
  crates/rust-analyzer/Cargo.toml
  crates/rust-analyzer/src/lib.rs
Labels: S-waiting-on-review

#19070 Remove mutable syntax tree shenanigans from adjustment hints
  crates/ide/src/inlay_hints/adjustment.rs
  crates/syntax/src/ast/prec.rs
Labels: S-waiting-on-review

#19072 Fix #19071: ensure `completion_item_hash` serializes items uniquely
  crates/rust-analyzer/src/lib.rs
Labels: S-waiting-on-review
